# CADPS2 - Single Gene Analysis in GP2 NBA data

In [1]:
analysis = "NBA"
# analysis = "WGS"

## Description

1. Description

- Getting Started
- Loading Python libraries
- Defining functions 
- Set Paths 
- Make working directory 

2. Installing packages

3. Copy over data

4. Create a covariate file with GP2 data

5. Annotation of the gene

6. Case/Control Frequencies

5. Calculate frequency in cases versus controls

6. Calculate frequency (homozygotes) in cases versus controls

7. Save out results

## Loading Python libraries

In [2]:
# Use the os package to interact with the environment
import os

#Import Sys
import sys as sys

# Use pathlib for file path manipulation
import pathlib
from pathlib import Path

# Parallel processing
from itertools import product
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

# Import subprocess for easier management of bash commands
import subprocess

# Bring in Pandas for Dataframe functionality
import pandas as pd

# Numpy for basics
import numpy as np

# Use StringIO for working with file contents
from io import StringIO

# Enable IPython to display matplotlib graphs
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib
import seaborn as sns

# Import date and time for timestamps
from datetime import datetime, date
import time


print("Date of first run: 06-15-2025")
print("Date of last edits: 07-30-2025")


### Last iteration
print("Last iteration at:", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

### Package versions

print(f'''
=========================
    PACKAGE VERSIONS
=========================
pandas: {pd.__version__}
numpy: {np.__version__}
matplotlib: {matplotlib.__version__}
seaborn: {sns.__version__}
''')

Date of first run: 06-15-2025
Date of last edits: 07-30-2025
Last iteration at: 2026-03-02 14:38:17

=========================
    PACKAGE VERSIONS
=========================
pandas: 2.2.1
numpy: 1.26.0
matplotlib: 3.10.1
seaborn: 0.13.2

## Set paths

### Release paths

In [3]:
## GP2 v11
REL11_PATH = pathlib.Path(pathlib.Path.home(), 'workspace/gp2_tier2_eu_release11')
!ls -hal {REL11_PATH}

total 21K
dr-xr-xr-x. 1 jupyter users   0 Mar  2 12:56 clinical_data
dr-xr-xr-x. 1 jupyter users   0 Mar  2 12:56 clinical_exomes
dr-xr-xr-x. 1 jupyter users   0 Mar  2 12:56 imputed_genotypes
dr-xr-xr-x. 1 jupyter users   0 Mar  2 12:56 meta_data
dr-xr-xr-x. 1 jupyter users   0 Mar  2 12:56 raw_genotypes
dr-xr-xr-x. 1 jupyter users   0 Mar  2 12:56 raw_genotypes_flipped
-r--r--r--. 1 jupyter users 21K Dec  2 04:24 README_R11.txt
dr-xr-xr-x. 1 jupyter users   0 Mar  2 12:56 wgs

In [4]:
# GP2 R11

CLINICAL_DATA_PATH = pathlib.Path(REL11_PATH, 'clinical_data/master_key_release11_final_vwb.csv')
EXTENDED_CLINICAL_DATA_PATH = pathlib.Path('REL11_PATH, clinical_data/r11_extended_clinical_data_vwb.csv')

IMPUTED_GENO_PATH = pathlib.Path(REL11_PATH, 'imputed_genotypes')
RAW_GENO_PATH = pathlib.Path(REL11_PATH, 'raw_genotypes')

RELATED_DATA_PATH = pathlib.Path(REL11_PATH, 'meta_data/related_samples')

In [5]:
## Use tree command to visualize directory structure
## To see more depth, adjust -L flag (e.g. 1, 2, 3)
! tree -L 1 {REL11_PATH}

/home/jupyter/workspace/gp2_tier2_eu_release11
├── clinical_data
├── clinical_exomes
├── imputed_genotypes
├── meta_data
├── raw_genotypes
├── raw_genotypes_flipped
├── README_R11.txt
└── wgs

7 directories, 1 file

## Workspace paths

In [ ]:
GENE_DATA = """
CADPS2 7 122318311 122886859
"""

In [7]:
GENE_DICT = {}
for line in GENE_DATA.strip().split("\n"):
    name, chrom, start, end = line.split()
    GENE_DICT[name] = {
        "CHR": chrom,
        "START": int(start),
        "END": int(end)
    }

In [8]:
print(GENE_DICT)

{'CADPS2': {'CHR': '7', 'START': 122318311, 'END': 122886859}}

In [9]:
## Define gene of interest
# GENE_NAME = "CADPS2"

for GENE in GENE_DICT:
    print(GENE)


RELEASE = "NBA_R11"

CADPS2

In [10]:
### Define ANCESTRIES as a python list
ANCESTRIES = ['AAC', 'AFR', 'AJ', 'AMR', 'CAS', 'EAS', 'EUR', 'FIN', 'MDE', 'SAS', 'CAH']

In [11]:
## Get main directories

GENE_NAME = "CADPS2"

TOP_DIR =   "/home/jupyter"
TOOL_DIR =  "/home/jupyter/tools"
HOME_DIR =  "/home/jupyter/workspace"
WS_DIR=     "/home/jupyter/workspace/ws_files/"
WORK_DIR =  "/home/jupyter/workspace/ws_files/NahuTestR11"
ANA_DIR =   f"/home/jupyter/workspace/ws_files/NahuTestR11/{analysis}"
RESU_DIR =  "/home/jupyter/workspace/ws_files/NahuTestR11/Results"

dirs = ("/home/jupyter/tools", "/home/jupyter/workspace/ws_files/NahuTestR11", f"/home/jupyter/workspace/ws_files/NahuTestR11/{analysis}")

## Subdirs for analyses
subdirs = ["InputFiles", "VariantDescriptives", "Association", "GLM", "Burden"]

for dir in dirs:
    os.makedirs(dir, exist_ok=True)       
    os.makedirs(f"{RESU_DIR}/{analysis}", exist_ok = True)         ## exist_ok = True checks if already created
for ANCESTRY in ANCESTRIES:
    for subdir in subdirs:
        os.makedirs(f"{ANA_DIR}/{ANCESTRY}/{subdir}", exist_ok = True)

## Install Packages

In [ ]:
%%capture
%%bash

# Install plink 1.9

## Change directory to tools
mkdir $TOOL_DIR
cd $TOOL_DIR

## ------------------------------## 
## Check if plink1.9 is installed
if test -e /home/jupyter/tools/plink1.9; then
    echo "Plink is already installed in /home/jupyter/tools"
else
    echo "Plink is not installed"

    cd /home/jupyter/tools

    wget -nc http://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20190304.zip 

    unzip -o plink_linux_x86_64_20190304.zip
    mv plink plink1.9
fi

## ------------------------------## 
## Check if plink2.0 is installed
if test -e /home/jupyter/tools/plink2; then
    echo "Plink2 is already installed in /home/jupyter/tools"
else
    echo "Plink2 is not installed"
    cd /home/jupyter/tools
    
    wget -nc http://s3.amazonaws.com/plink2-assets/plink2_linux_x86_64_latest.zip

    unzip -o plink2_linux_x86_64_latest.zip
fi

In [ ]:
# chmod (change permissions): plink1.9 and plink2 to make sure you have permission to run the program
! chmod u+x /home/jupyter/tools/plink1.9
! chmod u+x /home/jupyter/tools/plink2

In [ ]:
%%capture
%%bash

# Install ANNOVAR: We are adding the download link after registration on the annovar website
# https://www.openbioinformatics.org/annovar/annovar_download_form.php

if test -e /home/jupyter/tools/annovar; then
    echo "annovar is already installed in /home/jupyter/tools/notebooks"

else
    echo "annovar is not installed"
    cd /home/jupyter/tools
    
    wget -nc http://www.openbioinformatics.org/annovar/download/0wgxR2rIVP/annovar.latest.tar.gz
    
    tar -xvzf annovar.latest.tar.gz
fi

In [ ]:
%%capture
%%bash

cd /home/jupyter/tools/annovar/

# Install ANNOVAR: Download resources for annotation

#perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar dbnsfp47a humandb/ #latest version of dbNSFP
#perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar clinvar_20250721 humandb/
#perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar gnomad41_genome humandb/
#perl annotate_variation.pl -buildver hg38 -downdb -webfrom annovar gnomad41_exome humandb/

In [ ]:
%%capture
%%bash

#Install RVTESTS: Option 1 (~15min)
if test -e /home/jupyter/tools/rvtests; then
    echo "RVtests is already installed in /home/jupyter/tools/"
else
    echo "RVtests is not installed"
    
    mkdir /home/jupyter/tools/rvtests
    cd /home/jupyter/tools/rvtests
    
    wget https://github.com/zhanxw/rvtests/releases/download/v2.1.0/rvtests_linux64.tar.gz 
    
    tar -zxvf rvtests_linux64.tar.gz
fi

In [ ]:
! chmod 777 /home/jupyter/tools/rvtests/executable/rvtest

In [ ]:
! {TOOL_DIR}/rvtests/executable/rvtest --help

In [ ]:
## Download refFlat

! wget -O {TOOL_DIR}/refFlat_HG38_all_chr.txt.gz https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/refFlat.txt.gz 
! gunzip -f {TOOL_DIR}/refFlat_HG38_all_chr.txt.gz

In [ ]:
'''%%bash
cd /home/jupyter/tools/
rm *.zip
rm *.gz
rm toy*
rm prettify
rm vcf_subset
rm LICENSE
rm ./rvtests/*.gz
rm -r  ./rvtests/example'''

## Create a covariate file with GP2 data

In [83]:
# Let's load the master key
key1 = pd.read_csv(CLINICAL_DATA_PATH, low_memory=False)
print(f'Clinical data (num rows, num columns): {key1.shape}')
pd.set_option('display.max_columns', None)
key1.head()

Clinical data (num rows, num columns): (130274, 32)

,study,FID,GP2ID,nba,wgs,clinical_exome,extended_clinical_data,nba_prune_reason,nba_related,nba_label,wgs_prune_reason,wgs_label,study_arm,study_type,diagnosis,baseline_GP2_phenotype_for_qc,baseline_GP2_phenotype,biological_sex_for_qc,age_at_sample_collection,age_of_onset,age_at_diagnosis,age_at_death,age_at_last_follow_up,race_for_qc,family_history_for_qc,region_for_qc,manifest_id,genotyping_site,sample_type,amppd_wgs,GDPR,flag
0,24HR,24HR_000001,24HR_000001,1.0,1.0,NaN,NaN,NaN,NaN,EUR,NaN,EUR,Case,Case(/Control),PD,PD,PD,Female,NaN,NaN,NaN,NaN,NaN,Not Reported,Not Reported,USA,m1,Psomagen,DNA,NaN,0.0,NaN
1,24HR,24HR_000002,24HR_000002,1.0,1.0,NaN,NaN,NaN,NaN,EUR,NaN,EUR,Case,Case(/Control),PD,PD,PD,Male,NaN,NaN,NaN,NaN,NaN,Not Reported,Not Reported,USA,m1,Psomagen,DNA,NaN,0.0,NaN
2,24HR,24HR_000003,24HR_000003,1.0,1.0,NaN,NaN,NaN,NaN,EUR,NaN,EUR,Case,Case(/Control),PD,PD,PD,Male,NaN,NaN,NaN,NaN,NaN,Not Reported,Not Reported,USA,m1,Psomagen,DNA,NaN,0.0,NaN
3,24HR,24HR_000004,24HR_000004,1.0,1.0,NaN,NaN,NaN,NaN,EUR,NaN,EUR,Case,Case(/Control),PD,PD,PD,Male,NaN,NaN,NaN,NaN,NaN,Not Reported,Not Reported,USA,m1,Psomagen,DNA,NaN,0.0,NaN
4,24HR,24HR_000005,24HR_000005,1.0,1.0,NaN,NaN,NaN,NaN,EUR,NaN,EUR,Case,Case(/Control),PD,PD,PD,Male,NaN,NaN,NaN,NaN,NaN,Not Reported,Not Reported,USA,m1,Psomagen,DNA,NaN,0.0,NaN

In [84]:
# Subsetting to keep only a few columns 
key = key1[['GP2ID', 'GP2ID', 'baseline_GP2_phenotype_for_qc', 'biological_sex_for_qc', 'age_at_sample_collection', 'age_of_onset', 'nba_label','wgs_label']]

# 'nba_GP2sampleID_r11'
# Renaming the columns

key.columns = ['IID', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'nba_label', 'wgs_label']
key

,IID,IID1_OLD,phenotype,SEX,AGE,AAO,nba_label,wgs_label
0,24HR_000001,24HR_000001,PD,Female,NaN,NaN,EUR,EUR
1,24HR_000002,24HR_000002,PD,Male,NaN,NaN,EUR,EUR
2,24HR_000003,24HR_000003,PD,Male,NaN,NaN,EUR,EUR
3,24HR_000004,24HR_000004,PD,Male,NaN,NaN,EUR,EUR
4,24HR_000005,24HR_000005,PD,Male,NaN,NaN,EUR,EUR
...,...,...,...,...,...,...,...,...
130269,YMS_000080,YMS_000080,Other,Male,66.0,NaN,AJ,NaN
130270,YMS_000081,YMS_000081,Other,Male,71.0,NaN,AAC,NaN
130271,YMS_000082,YMS_000082,PD,Male,76.0,71.0,AJ,NaN
130272,YMS_000083,YMS_000083,Other,Male,69.0,NaN,AJ,NaN
130273,YMS_000084,YMS_000084,Other,Female,67.0,NaN,EUR,NaN

In [85]:
key["label"] = key["nba_label"].combine_first(key["wgs_label"])
key = key.drop(columns=["nba_label", "wgs_label"])
key

/tmp/ipykernel_658/428804967.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  key["label"] = key["nba_label"].combine_first(key["wgs_label"])

                IID     IID1_OLD phenotype     SEX   AGE   AAO label
0       24HR_000001  24HR_000001        PD  Female   NaN   NaN   EUR
1       24HR_000002  24HR_000002        PD    Male   NaN   NaN   EUR
2       24HR_000003  24HR_000003        PD    Male   NaN   NaN   EUR
3       24HR_000004  24HR_000004        PD    Male   NaN   NaN   EUR
4       24HR_000005  24HR_000005        PD    Male   NaN   NaN   EUR
...             ...          ...       ...     ...   ...   ...   ...
130269   YMS_000080   YMS_000080     Other    Male  66.0   NaN    AJ
130270   YMS_000081   YMS_000081     Other    Male  71.0   NaN   AAC
130271   YMS_000082   YMS_000082        PD    Male  76.0  71.0    AJ
130272   YMS_000083   YMS_000083     Other    Male  69.0   NaN    AJ
130273   YMS_000084   YMS_000084     Other  Female  67.0   NaN   EUR

[130274 rows x 7 columns]

In [86]:
for ANCESTRY in ANCESTRIES:
        ## To run analyses here
        
        print(f'\nWORKING ON: {ANCESTRY}')
            
        ## Subset to keep ANCESTRY of interest 
        ANCESTRY_key = key[key['label']==ANCESTRY].copy()
        ANCESTRY_key.reset_index(drop=True)
            
        # Load information about related individuals in the ANCESTRY analyzed
        related_df = pd.read_csv(f'{RELATED_DATA_PATH}/{ANCESTRY}_release11_vwb.related')
        print(f'Related individuals: {related_df.shape}')
        
        # Make a list of just one set of related people
        related_list = list(related_df['IID1'])
        
        # Check value counts of related and remove only one related individual
        ANCESTRY_key = ANCESTRY_key[~ANCESTRY_key["IID1_OLD"].isin(related_list)]
        # Check size
        print(f'Unrelated individuals: {ANCESTRY_key.shape}')
            
        # Convert phenotype to binary (1/2)
        ## Assign conditions so case=2 and controls=1, and -9 otherwise (matching PLINK convention)
        # PD = 2; control = 1
        pheno_mapping = {"PD": 2, "Control": 1}
        ANCESTRY_key['PHENO'] = ANCESTRY_key['phenotype'].map(pheno_mapping).astype('Int64')
    
        # Check value counts of pheno
        ANCESTRY_key['PHENO'].value_counts(dropna=False)
        
        ## Get the PCs
        pcs = pd.read_csv(f'{RAW_GENO_PATH}/{ANCESTRY}/{ANCESTRY}_release11_vwb.eigenvec', sep='\t')
        
        #Select just first 10 PCs
        selected_columns = ['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10']
        pcs = pd.DataFrame(data=pcs.iloc[:, 0:12].values, columns=selected_columns)
    
        # Drop the first row (since it's now the column names)
        pcs = pcs.drop(0)
    
        # Reset the index to remove any potential issues
        pcs = pcs.reset_index(drop=True)
        
        # Check size
        print(f'PCs: {pcs.shape}')
    
        # Check value counts of SEX
        sex_og_values = ANCESTRY_key['SEX'].value_counts(dropna=False)
        print(f'Sex value counts - original:\n {sex_og_values.to_string()}')
        
        # Convert sex to binary (1/2)
        ## Assign conditions so female=2 and men=1, and -9 otherwise (matching PLINK convention)
        # Female = 2; Male = 1
        sex_mapping = {"Female": 2, "Male": 1}
        ANCESTRY_key['SEX'] = ANCESTRY_key['SEX'].map(sex_mapping).astype('Int64')
        
        # Check value counts of SEX after recoding
        sex_recode_values = ANCESTRY_key['SEX'].value_counts(dropna=False)
        print(f'Sex value counts - recoded:\n{sex_recode_values.to_string()}')
        
        ## Make covariate file
        df = pd.merge(pcs, ANCESTRY_key, on='IID', how='left')
        print(f'\nCheck columns for covariate file: {df.columns}')
        
        #Make additional columns - FID, fatid and matid - these are needed for RVtests!!
        #RVtests needs the first 5 columns to be fid, iid, fatid, matid and sex otherwise it does not run correctly
        #Uppercase column name is ok
        #See https://zhanxw.github.io/rvtests/#phenotype-file
        df['FATID'] = 0
        df['MATID'] = 0
    
        ## Clean up and keep columns we need 
        final_df = df[['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10']].copy()
        final_df.columns = ['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10']
    
        print(f'\nCheck columns for Final covariate file: {final_df.columns}')
    
        ##DO NOT replace missing values with -9 as this is misinterpreted by RVtests - needs to be nonnumeric
        #Leave missing values as NA
        
        #Check number of PD cases missing age
        pd_missAge = final_df[(final_df['PHENO']==2)&(final_df['AGE'].isna())]
        print(f'Number of PD cases missing age: {pd_missAge.shape[0]}')
        
        #Check number of controls missing age
        control_missAge = final_df[(final_df['PHENO']==1)&(final_df['AGE'].isna())]
        print(f'Number of controls missing age: {control_missAge.shape[0]}')
    
        ## Make file of sample IDs to keep 
        samples_toKeep = final_df[['FID', 'IID']].copy()
        
        samplestokeep_path = pathlib.Path(pathlib.Path.home(), f'{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}.samplestokeep')
        
        # Create the output CSV file's parent folder in the cloud storage bucket, if it doesn't already exist.
        if not samplestokeep_path.parent.exists():
            !mkdir -p {samplestokeep_path.parent}
            print(f'Created {samplestokeep_path.parent}')
        
        samples_toKeep.to_csv(samplestokeep_path, sep = '\t', index=False, header=None)
    
        finaldf_path = pathlib.Path(pathlib.Path.home(), f'{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_covariate_file.txt')
        
        # Create the output CSV file's parent folder in the cloud storage bucket, if it doesn't already exist.
        if not finaldf_path.parent.exists():
            !mkdir -p {finaldf_path.parent}
            print(f'Created {finaldf_path.parent}')
        
        final_df.to_csv(finaldf_path, sep = '\t', na_rep='NA', index=False)

WORKING ON: AAC
Related individuals: (12, 9)
Unrelated individuals: (1584, 7)
PCs: (1381, 12)
Sex value counts - original:
 SEX
Female                        861
Male                          721
Other/Unknown/Not Reported      2
Sex value counts - recoded:
SEX
2       861
1       721
<NA>      2

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 82
Number of controls missing age: 22

WORKING ON: AFR
Related individuals: (429, 9)
Unrelated individuals: (7937, 7)
PCs: (7245, 12)
Sex value counts - original:
 SEX
Male                          4658
Female                        3277
Other/Unknown/Not Reported       2
Sex value counts - recoded:
SEX
1       4658
2       3277
<NA>       2

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 146
Number of controls missing age: 43

WORKING ON: AJ
Related individuals: (307, 9)
Unrelated individuals: (5078, 7)
PCs: (3988, 12)
Sex value counts - original:
 SEX
Male                          3096
Female                        1973
Other/Unknown/Not Reported       9
Sex value counts - recoded:
SEX
1       3096
2       1973
<NA>       9

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 164
Number of controls missing age: 249

WORKING ON: AMR
Related individuals: (211, 9)
Unrelated individuals: (4653, 7)
PCs: (3815, 12)
Sex value counts - original:
 SEX
Female                        2385
Male                          2267
Other/Unknown/Not Reported       1
Sex value counts - recoded:
SEX
2       2385
1       2267
<NA>       1

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 168
Number of controls missing age: 54

WORKING ON: CAS
Related individuals: (398, 9)
Unrelated individuals: (3147, 7)
PCs: (2800, 12)
Sex value counts - original:
 SEX
Female    1792
Male      1355
Sex value counts - recoded:
SEX
2    1792
1    1355

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 398
Number of controls missing age: 608

WORKING ON: EAS
Related individuals: (414, 9)
Unrelated individuals: (8762, 7)
PCs: (7964, 12)
Sex value counts - original:
 SEX
Male                          5130
Female                        3626
Other/Unknown/Not Reported       6
Sex value counts - recoded:
SEX
1       5130
2       3626
<NA>       6

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 129
Number of controls missing age: 1097

WORKING ON: EUR
Related individuals: (2857, 9)
Unrelated individuals: (82749, 7)
PCs: (71401, 12)
Sex value counts - original:
 SEX
Male                          46520
Female                        36078
Other/Unknown/Not Reported      151
Sex value counts - recoded:
SEX
1       46520
2       36078
<NA>      151

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 5367
Number of controls missing age: 4134

WORKING ON: FIN
Related individuals: (5, 9)
Unrelated individuals: (178, 7)
PCs: (153, 12)
Sex value counts - original:
 SEX
Female    99
Male      79
Sex value counts - recoded:
SEX
2    99
1    79

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 57
Number of controls missing age: 6

WORKING ON: MDE
Related individuals: (76, 9)
Unrelated individuals: (2878, 7)
PCs: (2472, 12)
Sex value counts - original:
 SEX
Male                          1488
Female                        1389
Other/Unknown/Not Reported       1
Sex value counts - recoded:
SEX
1       1488
2       1389
<NA>       1

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 247
Number of controls missing age: 574

WORKING ON: SAS
Related individuals: (121, 9)
Unrelated individuals: (1426, 7)
PCs: (1289, 12)
Sex value counts - original:
 SEX
Male      910
Female    516
Sex value counts - recoded:
SEX
1    910
2    516

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 61
Number of controls missing age: 83

WORKING ON: CAH
Related individuals: (35, 9)
Unrelated individuals: (1969, 7)
PCs: (1267, 12)
Sex value counts - original:
 SEX
Male                          1044
Female                         910
Other/Unknown/Not Reported      15
Sex value counts - recoded:
SEX
1       1044
2        910
<NA>      15

Check columns for covariate file: Index(['FID', 'IID', 'PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8',
       'PC9', 'PC10', 'IID1_OLD', 'phenotype', 'SEX', 'AGE', 'AAO', 'label',
       'PHENO'],
      dtype='object')

Check columns for Final covariate file: Index(['FID', 'IID', 'FATID', 'MATID', 'SEX', 'AGE', 'PHENO', 'PC1', 'PC2',
       'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10'],
      dtype='object')
Number of PD cases missing age: 141
Number of controls missing age: 50

## Annotation of the gene

### Extract the region using PLINK in hg38

- Extract *CADPS2* gene
- *CADPS2* coordinates: Chromosome 7: 122,318,311-122,886,859 (GRCh38/hg38)
- Source: https://www.genecards.org/cgi-bin/carddisp.pl?gene=CADPS2

In [87]:
## extract region using plink

def regionExtractor(number, startBP, endBP, ANCESTRY):
    
    ## Analysis start time
    ts_start = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   ANALYSIS START:   {ts_start}   =====================\n")
    
    ## Get ANCESTRY name
    print(f"\nExtracting {GENE_NAME} from {ANCESTRY} NBA Release 11 data.")
    
    ## Create directory for ANCESTRY
    print(f"\nStoring output plink2 files in {ANA_DIR}/{ANCESTRY}\n\n")

    inputRawFile = f"{IMPUTED_GENO_PATH}/{ANCESTRY}/chr{number}_{ANCESTRY}_release11_vwb"
    outputPrefix = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_{GENE_NAME}"
    
    ## Define plink2 command for extraction
    regionExtractor = [
        f"{TOOL_DIR}/plink2",
        "--pfile", inputRawFile,
        "--chr", str(number),
        "--from-bp", str(startBP),
        "--to-bp", str(endBP),
        "--extract-if-info", "R2>=0.8",
        "--mac", "2",
        "--hwe", "0.0001", 'keep-fewhet',
        "--max-maf", "0.05",
        "--make-pgen",
        "--out", outputPrefix
    ]

    ## Run plink2 command as bash subprocess
    result = subprocess.run(regionExtractor, capture_output=True, text=True)
    print(result.stdout)
    print(result.stderr)

    
    vcfConverter = [
        f"{TOOL_DIR}/plink2",
        "--pfile", outputPrefix,
        "--recode", "vcf", "id-paste=iid",
        "--out", outputPrefix     
    ]

    ## Run plink2 command as bash subprocess
    subprocess.run(vcfConverter, check=True)
    
    vcfGzip = [
        "bgzip",
        "-f", f"{outputPrefix}.vcf"
    ]

    ## Run plink2 command as bash subprocess
    subprocess.run(vcfGzip, check=True)
    
    vcfIndex = [
        "tabix",
        "-f", "-p", "vcf", f"{outputPrefix}.vcf.gz"     
    ]    
    ## Run plink2 command as bash subprocess
    subprocess.run(vcfIndex, check=True)
    
    
    ## Analysis end time
    ts_finish = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   ANALYSIS END:   {ts_finish}   =====================\n")
    
    ## Return ANCESTRY, position and gene
    return f"Extracted: {ANCESTRY}, chr{number}:{startBP}:{endBP} for {GENE_NAME}"

In [88]:
for GENE_NAME in GENE_DICT:
    max_workers = max(1, len(ANCESTRIES) // 2)
    BUILD = "hg38"
    chrom = GENE_DICT[GENE_NAME]["CHR"]
    startBP = str(GENE_DICT[GENE_NAME]["START"])
    endBP = str(GENE_DICT[GENE_NAME]["END"])
    number = chrom.replace("chr", "")  # remove "chr" if needed

    print(f"""\nRegion of interest: chr{number}:{startBP}:{endBP} (build version {BUILD}), {GENE_NAME}\nANCESTRIES to extract: {ANCESTRIES}""")

    for ANCESTRY in ANCESTRIES:
        print(f'\nWORKING ON: {ANCESTRY}\n')
        BUILD = "hg38"
        
        regionExtractor(7, 122318311, 122886859, f"{ANCESTRY}")

Region of interest: chr7:122318311:122886859 (build version hg38), CADPS2
ANCESTRIES to extract: ['AAC', 'AFR', 'AJ', 'AMR', 'CAS', 'EAS', 'EUR', 'FIN', 'MDE', 'SAS', 'CAH']

WORKING ON: AAC



=============   ANALYSIS START:   Date: 2026-02-25   Time: 19-28-17   =====================


Extracting CADPS2 from AAC NBA Release 11 data.

Storing output plink2 files in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.log.
Options in effect:
  --chr 7
  --extract-if-info R2>=0.8
  --from-bp 122318311
  --hwe 0.0001 keep-fewhet
  --mac 2
  --make-pgen
  --max-maf 0.05
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AAC/chr7_AAC_release11_vwb
  --to-bp 122886859

Start time: Wed Feb 25 19:28:18 2026
104614 MiB RAM detected, ~94647 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
1382 samples (755 females, 627 males; 1382 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AAC/chr7_AAC_release11_vwb.psam.
3554777 variants in
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AAC/chr7_AAC_release11_vwb.pvar;
397889 excluded by --chr + --extract-if-info, 3156888 remaining.
1 binary phenotype loaded (478 cases, 816 controls).
Calculating allele frequencies... done.
--hwe keep-fewhet: 0 variants removed due to Hardy-Weinberg exact test
(founders only).
5558 variants removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
5309 variants remaining after main filters.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.psam
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.pvar
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.pgen
... done.
End time: Wed Feb 25 19:28:22 2026


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.log.
Options in effect:
  --export vcf id-paste=iid
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2
  --pfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2

Start time: Wed Feb 25 19:28:23 2026
104614 MiB RAM detected, ~94471 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
1382 samples (755 females, 627 males; 1382 founders) loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.psam.
5309 variants loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.pvar.
1 binary phenotype loaded (478 cases, 816 controls).
--export vcf to
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.vcf
done.
End time: Wed Feb 25 19:28:23 2026


=============   ANALYSIS END:   Date: 2026-02-25   Time: 19-28-24   =====================


WORKING ON: AFR



=============   ANALYSIS START:   Date: 2026-02-25   Time: 19-28-24   =====================


Extracting CADPS2 from AFR NBA Release 11 data.

Storing output plink2 files in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.log.
Options in effect:
  --chr 7
  --extract-if-info R2>=0.8
  --from-bp 122318311
  --hwe 0.0001 keep-fewhet
  --mac 2
  --make-pgen
  --max-maf 0.05
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AFR/chr7_AFR_release11_vwb
  --to-bp 122886859

Start time: Wed Feb 25 19:28:24 2026
104614 MiB RAM detected, ~94419 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
7246 samples (3026 females, 4220 males; 7246 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AFR/chr7_AFR_release11_vwb.psam.
4814434 variants in
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AFR/chr7_AFR_release11_vwb.pvar;
1568162 excluded by --chr + --extract-if-info, 3246272 remaining.
1 binary phenotype loaded (2549 cases, 4367 controls).
Calculating allele frequencies... done.
--hwe keep-fewhet: 0 variants removed due to Hardy-Weinberg exact test
(founders only).
4539 variants removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
6942 variants remaining after main filters.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.psam
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.pvar
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.pgen
... done.
End time: Wed Feb 25 19:28:32 2026


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.log.
Options in effect:
  --export vcf id-paste=iid
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2
  --pfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2

Start time: Wed Feb 25 19:28:32 2026
104614 MiB RAM detected, ~94478 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
7246 samples (3026 females, 4220 males; 7246 founders) loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.psam.
6942 variants loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.pvar.
1 binary phenotype loaded (2549 cases, 4367 controls).
--export vcf to
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.vcf
done.
End time: Wed Feb 25 19:28:34 2026


=============   ANALYSIS END:   Date: 2026-02-25   Time: 19-28-36   =====================


WORKING ON: AJ



=============   ANALYSIS START:   Date: 2026-02-25   Time: 19-28-36   =====================


Extracting CADPS2 from AJ NBA Release 11 data.

Storing output plink2 files in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.log.
Options in effect:
  --chr 7
  --extract-if-info R2>=0.8
  --from-bp 122318311
  --hwe 0.0001 keep-fewhet
  --mac 2
  --make-pgen
  --max-maf 0.05
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AJ/chr7_AJ_release11_vwb
  --to-bp 122886859

Start time: Wed Feb 25 19:28:37 2026
104614 MiB RAM detected, ~94521 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
3989 samples (1553 females, 2436 males; 3989 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AJ/chr7_AJ_release11_vwb.psam.
1468251 variants in
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AJ/chr7_AJ_release11_vwb.pvar;
175518 excluded by --chr + --extract-if-info, 1292733 remaining.
1 binary phenotype loaded (1810 cases, 529 controls).
Calculating allele frequencies... done.
--hwe keep-fewhet: 0 variants removed due to Hardy-Weinberg exact test
(founders only).
1661 variants removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
2665 variants remaining after main filters.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.psam
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.pvar
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.pgen
... done.
End time: Wed Feb 25 19:28:39 2026


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.log.
Options in effect:
  --export vcf id-paste=iid
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2
  --pfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2

Start time: Wed Feb 25 19:28:39 2026
104614 MiB RAM detected, ~94546 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
3989 samples (1553 females, 2436 males; 3989 founders) loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.psam.
2665 variants loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.pvar.
1 binary phenotype loaded (1810 cases, 529 controls).
--export vcf to
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.vcf
done.
End time: Wed Feb 25 19:28:40 2026


=============   ANALYSIS END:   Date: 2026-02-25   Time: 19-28-41   =====================


WORKING ON: AMR



=============   ANALYSIS START:   Date: 2026-02-25   Time: 19-28-41   =====================


Extracting CADPS2 from AMR NBA Release 11 data.

Storing output plink2 files in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.log.
Options in effect:
  --chr 7
  --extract-if-info R2>=0.8
  --from-bp 122318311
  --hwe 0.0001 keep-fewhet
  --mac 2
  --make-pgen
  --max-maf 0.05
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AMR/chr7_AMR_release11_vwb
  --to-bp 122886859

Start time: Wed Feb 25 19:28:41 2026
104614 MiB RAM detected, ~94527 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
3816 samples (1961 females, 1855 males; 3816 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AMR/chr7_AMR_release11_vwb.psam.
3747436 variants in
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/AMR/chr7_AMR_release11_vwb.pvar;
1241895 excluded by --chr + --extract-if-info, 2505541 remaining.
1 binary phenotype loaded (2122 cases, 1487 controls).
Calculating allele frequencies... done.
--hwe keep-fewhet: 0 variants removed due to Hardy-Weinberg exact test
(founders only).
4553 variants removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
4720 variants remaining after main filters.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.psam
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.pvar
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.pgen
... done.
End time: Wed Feb 25 19:28:46 2026

Warning: --hwe observation counts vary by more than 10%.0 Consider using --hwe
with a sample-size term (e.g. "--hwe 1e-5 0.001 keep-fewhet" results in a
threshold of 1e-6 with 1000 observations, 1e-7 with 2000 observations, etc.),
and/or filtering out high-missingness variants with --geno.

PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.log.
Options in effect:
  --export vcf id-paste=iid
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2
  --pfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2

Start time: Wed Feb 25 19:28:46 2026
104614 MiB RAM detected, ~94447 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
3816 samples (1961 females, 1855 males; 3816 founders) loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.psam.
4720 variants loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.pvar.
1 binary phenotype loaded (2122 cases, 1487 controls).
--export vcf to
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.vcf
done.
End time: Wed Feb 25 19:28:47 2026


=============   ANALYSIS END:   Date: 2026-02-25   Time: 19-28-48   =====================


WORKING ON: CAS



=============   ANALYSIS START:   Date: 2026-02-25   Time: 19-28-48   =====================


Extracting CADPS2 from CAS NBA Release 11 data.

Storing output plink2 files in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.log.
Options in effect:
  --chr 7
  --extract-if-info R2>=0.8
  --from-bp 122318311
  --hwe 0.0001 keep-fewhet
  --mac 2
  --make-pgen
  --max-maf 0.05
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/CAS/chr7_CAS_release11_vwb
  --to-bp 122886859

Start time: Wed Feb 25 19:28:48 2026
104614 MiB RAM detected, ~94456 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
2801 samples (1602 females, 1199 males; 2801 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/CAS/chr7_CAS_release11_vwb.psam.
2711622 variants in
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/CAS/chr7_CAS_release11_vwb.pvar;
1340560 excluded by --chr + --extract-if-info, 1371062 remaining.
1 binary phenotype loaded (1053 cases, 1371 controls).
Calculating allele frequencies... done.
--hwe keep-fewhet: 0 variants removed due to Hardy-Weinberg exact test
(founders only).
2581 variants removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
2522 variants remaining after main filters.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.psam
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.pvar
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.pgen
... done.
End time: Wed Feb 25 19:28:52 2026

Warning: --hwe observation counts vary by more than 10%.0 Consider using --hwe
with a sample-size term (e.g. "--hwe 1e-5 0.001 keep-fewhet" results in a
threshold of 1e-6 with 1000 observations, 1e-7 with 2000 observations, etc.),
and/or filtering out high-missingness variants with --geno.

PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.log.
Options in effect:
  --export vcf id-paste=iid
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2
  --pfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2

Start time: Wed Feb 25 19:28:52 2026
104614 MiB RAM detected, ~94445 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
2801 samples (1602 females, 1199 males; 2801 founders) loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.psam.
2522 variants loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.pvar.
1 binary phenotype loaded (1053 cases, 1371 controls).
--export vcf to
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.vcf
done.
End time: Wed Feb 25 19:28:53 2026


=============   ANALYSIS END:   Date: 2026-02-25   Time: 19-28-53   =====================


WORKING ON: EAS



=============   ANALYSIS START:   Date: 2026-02-25   Time: 19-28-53   =====================


Extracting CADPS2 from EAS NBA Release 11 data.

Storing output plink2 files in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS


PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.log.
Options in effect:
  --chr 7
  --extract-if-info R2>=0.8
  --from-bp 122318311
  --hwe 0.0001 keep-fewhet
  --mac 2
  --make-pgen
  --max-maf 0.05
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2
  --pfile /home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/EAS/chr7_EAS_release11_vwb
  --to-bp 122886859

Start time: Wed Feb 25 19:28:53 2026
104614 MiB RAM detected, ~94424 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
7965 samples (3328 females, 4637 males; 7965 founders) loaded from
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/EAS/chr7_EAS_release11_vwb.psam.
2935339 variants in
/home/jupyter/workspace/gp2_tier2_eu_release11/imputed_genotypes/EAS/chr7_EAS_release11_vwb.pvar;
2009836 excluded by --chr + --extract-if-info, 925503 remaining.
1 binary phenotype loaded (3083 cases, 2787 controls).
Calculating allele frequencies... done.
--hwe keep-fewhet: 0 variants removed due to Hardy-Weinberg exact test
(founders only).
1395 variants removed due to allele frequency threshold(s)
(--maf/--max-maf/--mac/--max-mac).
2680 variants remaining after main filters.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.psam
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.pvar
... done.
Writing
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.pgen
... done.
End time: Wed Feb 25 19:28:58 2026

Warning: --hwe observation counts vary by more than 10%.0 Consider using --hwe
with a sample-size term (e.g. "--hwe 1e-5 0.001 keep-fewhet" results in a
threshold of 1e-6 with 1000 observations, 1e-7 with 2000 observations, etc.),
and/or filtering out high-missingness variants with --geno.

PLINK v2.0.0-a.7LM 64-bit Intel (18 Nov 2025)       cog-genomics.org/plink/2.0/
(C) 2005-2025 Shaun Purcell, Christopher Chang    GNU General Public License v3
Logging to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.log.
Options in effect:
  --export vcf id-paste=iid
  --out /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2
  --pfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2

Start time: Wed Feb 25 19:28:59 2026
104614 MiB RAM detected, ~94491 available; reserving 52307 MiB for main
workspace.
Using up to 16 threads (change this with --threads).
7965 samples (3328 females, 4637 males; 7965 founders) loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.psam.
2680 variants loaded from
/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.pvar.

## Annotate using ANNOVAR

In [15]:
def regionAnnotator(GENE_NAME, ANCESTRY):
    print(f"Extracting {GENE_NAME} from {ANCESTRY} NBA Release 11 data.")
    
    input_vcf = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_{GENE_NAME}.vcf.gz"
    output_base = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_{GENE_NAME}.annovar"
    
    cmd = [
        "perl", f"{TOOL_DIR}/annovar/table_annovar.pl",
        input_vcf,
        f"{TOOL_DIR}/annovar/humandb/",
        "-buildver", "hg38",
        "-out", output_base,
        "-remove", 
        "-protocol", "refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome", 
        "-operation", "g,f,f,f,f", 
        "--nopolish",
        "-nastring", ".",
        "-vcfinput"
    ]
    
    try:
        subprocess.run(cmd, check=True)
        print(f"\nSUCCESS: {ANCESTRY}, {GENE_NAME}\n")
    except subprocess.CalledProcessError as e:
        print(f"\nERROR in {ANCESTRY}, {GENE_NAME}: {e}\n")
    
    return f"{output_base}.hg38_multianno.txt" # Return the path so you can use it

# Logic for workers and product
def regionAnnotator_wrapper(args):
    return regionAnnotator(*args)

# Explicitly use .keys() if GENE_DICT is a dictionary
args = list(product(GENE_DICT.keys(), ANCESTRIES)) 

max_workers = max(1, len(ANCESTRIES) // 2)

with ProcessPoolExecutor(max_workers=max_workers) as executor:
    # results will now be a list of paths to your output files
    results = list(executor.map(regionAnnotator_wrapper, args))

Extracting CADPS2 from AFR NBA Release 11 data.Extracting CADPS2 from AJ NBA Release 11 data.Extracting CADPS2 from CAS NBA Release 11 data.Extracting CADPS2 from AMR NBA Release 11 data.Extracting CADPS2 from AAC NBA Release 11 data.

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.avinput>

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.avinput>

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.avinput>

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.avinput>

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.avinput>
NOTICE: Finished reading 2541 lines from VCF file
NOTICE: A total of 2522 locus in VCF file passed QC threshold, representing 2329 SNPs (1592 transitions and 737 transversions) and 193 indels/substitutions
NOTICE: Finished writing allele frequencies based on 6523529 SNP genotypes (4459192 transitions and 2064337 transversions) and 540593 indels/substitutions for 2801 samples

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.refGene.exonic_variant_function
NOTICE: Finished reading 5328 lines from VCF filer/tools/annovar/humandb/hg38_refGene.txt ...
NOTICE: A total of 5309 locus in VCF file passed QC threshold, representing 4831 SNPs (3320 transitions and 1511 transversions) and 478 indels/substitutions
NOTICE: Finished writing allele frequencies based on 6676442 SNP genotypes (4588240 transitions and 2088202 transversions) and 660596 indels/substitutions for 1382 samples

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.refGene.exonic_variant_function
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Processing next batch with 2522 unique variants in 2522 input lines
NOTICE: Processing next batch with 5309 unique variants in 5309 input lines
NOTICE: Reading FASTA sequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ... Done with 17 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_clinvar_20250721_filtered
Done with 17 sequencessequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ...
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
NOTICE: Processing next batch with 2522 unique variants in 2522 input lines
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_clinvar_20250721_filtered
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 29
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Processing next batch with 5309 unique variants in 5309 input lines
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 30
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...
NOTICE: Processing next batch with 2522 unique variants in 2522 input lines
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 29
NOTICE: Processing next batch with 5309 unique variants in 5309 input linesbnsfp47a.txt...
NOTICE: Finished reading 2684 lines from VCF file
NOTICE: A total of 2665 locus in VCF file passed QC threshold, representing 2443 SNPs (1661 transitions and 782 transversions) and 222 indels/substitutions
NOTICE: Finished writing allele frequencies based on 9745127 SNP genotypes (6625729 transitions and 3119398 transversions) and 885558 indels/substitutions for 3989 samples
Done

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.refGene.exonic_variant_function
NOTICE: Reading gene annotation from /home/jupyter/tools/annovar/humandb/hg38_refGene.txt ... -----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_gnomad41_genome_filtered
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 44
NOTICE: Processing next batch with 2522 unique variants in 2522 input linesbnsfp47a.txt...
Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_gnomad41_genome_filtered
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Processing next batch with 5309 unique variants in 5309 input lines
NOTICE: Processing next batch with 2665 unique variants in 2665 input lines
NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 560
NOTICE: Reading FASTA sequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ... NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 569
Done with 17 sequencesr database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_genome.txt...
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_clinvar_20250721_filtered
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_gnomad41_exome_filtered
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Processing next batch with 2665 unique variants in 2665 input lines
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_gnomad41_exome_filtered
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 30
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 75
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_exome.txt...
Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Processing next batch with 5309 unique variants in 5309 input lines
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_multianno.txt
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 77
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_exome.txt...
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_multianno.txt
NOTICE: Processing next batch with 2665 unique variants in 2665 input lines
-----------------------------------------------------------------
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2.annovar.hg38_multianno.vcf
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2.annovar.hg38_multianno.txt
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 25
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_dbnsfp47a.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>

SUCCESS: CAS, CADPS2

Extracting CADPS2 from EAS NBA Release 11 data.

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.avinput>
NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 561
NOTICE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_genome.txt...

SUCCESS: AAC, CADPS2

Extracting CADPS2 from FIN NBA Release 11 data.

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.avinput>
NOTICE: Finished reading 656 lines from VCF file
NOTICE: A total of 637 locus in VCF file passed QC threshold, representing 584 SNPs (390 transitions and 194 transversions) and 53 indels/substitutions
NOTICE: Finished writing allele frequencies based on 89936 SNP genotypes (60060 transitions and 29876 transversions) and 8162 indels/substitutions for 154 samples

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.refGene.exonic_variant_function
NOTICE: Reading gene annotation from /home/jupyter/tools/annovar/humandb/hg38_refGene.txt ... Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_gnomad41_exome_filtered
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Processing next batch with 637 unique variants in 637 input lines
NOTICE: Processing next batch with 2665 unique variants in 2665 input lines
NOTICE: Reading FASTA sequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ... Done with 17 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
NOTICE: Finished reading 4739 lines from VCF file
NOTICE: A total of 4720 locus in VCF file passed QC threshold, representing 4318 SNPs (2967 transitions and 1351 transversions) and 402 indels/substitutions
NOTICE: Finished writing allele frequencies based on 16477488 SNP genotypes (11322072 transitions and 5155416 transversions) and 1534032 indels/substitutions for 3816 samples

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 75
-----------------------------------------------------------------ndb/hg38_gnomad41_exome.txt...
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.refGene.exonic_variant_function
-----------------------------------------------------------------humandb/hg38_refGene.txt ...
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_clinvar_20250721_filtered
NOTICE: Processing next batch with 637 unique variants in 637 input lines
Done
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 20
NOTICE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...Done
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_multianno.txt
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Processing next batch with 637 unique variants in 637 input lines
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 8
NOTICE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_dbnsfp47a.txt...Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_gnomad41_genome_filtered
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_multianno.txt
NOTICE: Processing next batch with 637 unique variants in 637 input lines
-----------------------------------------------------------------
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2.annovar.hg38_multianno.vcf
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 375
NOTICE: Processing next batch with 4720 unique variants in 4720 input linesnomad41_genome.txt...
Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_gnomad41_exome_filtered
NOTICE: Processing next batch with 637 unique variants in 637 input lines
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 47
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_exome.txt...
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_multianno.txt
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_multianno.txt
-----------------------------------------------------------------
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2.annovar.hg38_multianno.vcf

SUCCESS: FIN, CADPS2

Extracting CADPS2 from MDE NBA Release 11 data.

SUCCESS: AJ, CADPS2

Extracting CADPS2 from SAS NBA Release 11 data.

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.avinput>

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.avinput>
NOTICE: Reading FASTA sequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ... Done with 17 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_clinvar_20250721_filtered
NOTICE: Processing next batch with 4720 unique variants in 4720 input lines
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 30
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Processing next batch with 4720 unique variants in 4720 input lines
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 49
NOTICE: Finished reading 2058 lines from VCF fileols/annovar/humandb/hg38_dbnsfp47a.txt...
NOTICE: A total of 2039 locus in VCF file passed QC threshold, representing 1838 SNPs (1259 transitions and 579 transversions) and 201 indels/substitutions
NOTICE: Finished writing allele frequencies based on 2371020 SNP genotypes (1624110 transitions and 746910 transversions) and 259290 indels/substitutions for 1290 samples

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.refGene.exonic_variant_function
NOTICE: Reading gene annotation from /home/jupyter/tools/annovar/humandb/hg38_refGene.txt ... Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_gnomad41_genome_filtered
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Processing next batch with 2039 unique variants in 2039 input lines
NOTICE: Processing next batch with 4720 unique variants in 4720 input lines
NOTICE: Reading FASTA sequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ... Done with 17 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_clinvar_20250721_filtered
NOTICE: Processing next batch with 2039 unique variants in 2039 input lines
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 28
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Processing next batch with 2039 unique variants in 2039 input lines
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 23
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_dbnsfp47a.txt...
NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 569
-----------------------------------------------------------------ndb/hg38_gnomad41_genome.txt...
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_gnomad41_genome_filtered
NOTICE: Processing next batch with 2039 unique variants in 2039 input lines
Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_gnomad41_exome_filtered
NOTICE: Finished reading 2486 lines from VCF file
NOTICE: A total of 2467 locus in VCF file passed QC threshold, representing 2262 SNPs (1548 transitions and 714 transversions) and 205 indels/substitutions
NOTICE: Finished writing allele frequencies based on 5593926 SNP genotypes (3828204 transitions and 1765722 transversions) and 506965 indels/substitutions for 2473 samples

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.refGene.exonic_variant_function
NOTICE: Reading gene annotation from /home/jupyter/tools/annovar/humandb/hg38_refGene.txt ... NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 542
NOTICE: Processing next batch with 4720 unique variants in 4720 input linesnomad41_genome.txt...
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 77
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_gnomad41_exome_filtered
Done
NOTICE: Processing next batch with 2039 unique variants in 2039 input lines
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_multianno.txt
NOTICE: Processing next batch with 2467 unique variants in 2467 input lines
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 71
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_exome.txt...
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_multianno.txt
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_multianno.txt
-----------------------------------------------------------------humandb/hg38_refGeneMrna.fa ...
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2.annovar.hg38_multianno.vcf
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_multianno.txt
Done with 17 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
-----------------------------------------------------------------
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2.annovar.hg38_multianno.vcf
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_clinvar_20250721_filtered

SUCCESS: SAS, CADPS2

Extracting CADPS2 from CAH NBA Release 11 data.

NOTICE: Processing next batch with 2467 unique variants in 2467 input lines

NOTICE: Running with system command <convert2annovar.pl  -includeinfo -allsample -withfreq -format vcf4 /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.vcf.gz > /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.avinput>
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 30
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Processing next batch with 2467 unique variants in 2467 input lines
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 26
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_dbnsfp47a.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_gnomad41_genome_filtered
NOTICE: Processing next batch with 2467 unique variants in 2467 input lines
NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 558
NOTICE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_genome.txt...

SUCCESS: AMR, CADPS2

Done
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_gnomad41_exome_filtered
NOTICE: Processing next batch with 2467 unique variants in 2467 input lines
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 76
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_exome.txt...
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_multianno.txt
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_multianno.txt
-----------------------------------------------------------------
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2.annovar.hg38_multianno.vcf

SUCCESS: MDE, CADPS2

NOTICE: Finished reading 5380 lines from VCF file
NOTICE: A total of 5361 locus in VCF file passed QC threshold, representing 4879 SNPs (3378 transitions and 1501 transversions) and 482 indels/substitutions
NOTICE: Finished writing allele frequencies based on 6186572 SNP genotypes (4283304 transitions and 1903268 transversions) and 611176 indels/substitutions for 1268 samples

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.refGene.exonic_variant_function
NOTICE: Reading gene annotation from /home/jupyter/tools/annovar/humandb/hg38_refGene.txt ... Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Finished reading 2699 lines from VCF file
NOTICE: A total of 2680 locus in VCF file passed QC threshold, representing 2432 SNPs (1615 transitions and 817 transversions) and 248 indels/substitutions
NOTICE: Finished writing allele frequencies based on 19370880 SNP genotypes (12863475 transitions and 6507405 transversions) and 1975320 indels/substitutions for 7965 samples

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.refGene.exonic_variant_function
NOTICE: Processing next batch with 5361 unique variants in 5361 input lines38_refGene.txt ...
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes
NOTICE: Reading FASTA sequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ... Done with 17 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_clinvar_20250721_filtered
NOTICE: Processing next batch with 5361 unique variants in 5361 input lines
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 30
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Processing next batch with 5361 unique variants in 5361 input lines
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 53
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_dbnsfp47a.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Processing next batch with 2680 unique variants in 2680 input lines
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_gnomad41_genome_filtered
NOTICE: Processing next batch with 5361 unique variants in 5361 input lines
NOTICE: Reading FASTA sequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ... Done with 17 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_clinvar_20250721_filtered
NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 569
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_genome.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Processing next batch with 2680 unique variants in 2680 input lines
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_gnomad41_exome_filtered
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 30
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...
NOTICE: Processing next batch with 5361 unique variants in 5361 input lines
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 77
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_exome.txt...
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_multianno.txt
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_multianno.txt
NOTICE: Processing next batch with 2680 unique variants in 2680 input lines
-----------------------------------------------------------------
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2.annovar.hg38_multianno.vcf
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 30
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_dbnsfp47a.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_gnomad41_genome_filtered

SUCCESS: CAH, CADPS2

NOTICE: Processing next batch with 2680 unique variants in 2680 input lines
NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 555
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_genome.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_gnomad41_exome_filtered
NOTICE: Processing next batch with 2680 unique variants in 2680 input lines
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 76
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_exome.txt...
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_multianno.txt
NOTICE: Finished reading 6961 lines from VCF file
NOTICE: A total of 6942 locus in VCF file passed QC threshold, representing 6336 SNPs (4275 transitions and 2061 transversions) and 606 indels/substitutions
NOTICE: Finished writing allele frequencies based on 45910656 SNP genotypes (30976650 transitions and 14934006 transversions) and 4391076 indels/substitutions for 7246 samples
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_multianno.txt
-----------------------------------------------------------------
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2.annovar.hg38_multianno.vcf

NOTICE: Running with system command </home/jupyter/tools/annovar/table_annovar.pl /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar -remove -protocol refGene,clinvar_20250721,dbnsfp47a,gnomad41_genome,gnomad41_exome -operation g,f,f,f,f --nopolish -nastring . -otherinfo>
-----------------------------------------------------------------
NOTICE: Processing operation=g protocol=refGene

NOTICE: Running with system command <annotate_variation.pl -geneanno -buildver hg38 -dbtype refGene -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.refGene -exonsort -nofirstcodondel /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/>
NOTICE: Output files are written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.refGene.variant_function, /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.refGene.exonic_variant_function
Done with 88819 transcripts (including 21511 without coding sequence annotation) for 28307 unique genes

SUCCESS: EAS, CADPS2

NOTICE: Processing next batch with 6942 unique variants in 6942 input lines
NOTICE: Reading FASTA sequences from /home/jupyter/tools/annovar/humandb/hg38_refGeneMrna.fa ... Done with 17 sequences
WARNING: A total of 606 sequences will be ignored due to lack of correct ORF annotation
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_clinvar_20250721_filtered
NOTICE: Processing next batch with 6942 unique variants in 6942 input lines
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 30
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=dbnsfp47a
NOTICE: Finished reading 149 column headers for '-dbtype dbnsfp47a'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype dbnsfp47a -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_dbnsfp47a_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_dbnsfp47a_filtered
NOTICE: Processing next batch with 6942 unique variants in 6942 input lines
NOTICE: Database index loaded. Total number of bins is 556674 and the number of bins to be scanned is 58
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_dbnsfp47a.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_genome
NOTICE: Finished reading 19 column headers for '-dbtype gnomad41_genome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_genome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_gnomad41_genome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_gnomad41_genome_filtered
NOTICE: Processing next batch with 6942 unique variants in 6942 input lines
NOTICE: Database index loaded. Total number of bins is 2858148 and the number of bins to be scanned is 569
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_genome.txt...
-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=gnomad41_exome
NOTICE: Finished reading 18 column headers for '-dbtype gnomad41_exome'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype gnomad41_exome -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_gnomad41_exome_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_gnomad41_exome_filtered
NOTICE: Processing next batch with 6942 unique variants in 6942 input lines
NOTICE: Database index loaded. Total number of bins is 431759 and the number of bins to be scanned is 77
DoneCE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_gnomad41_exome.txt...
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_multianno.txt
NOTICE: Reading from /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_multianno.txt
-----------------------------------------------------------------
NOTICE: VCF output is written to /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2.annovar.hg38_multianno.vcf

SUCCESS: AFR, CADPS2

In [13]:
for ANCESTRY in ANCESTRIES:
    anno_dir = f"{ANA_DIR}/{ANCESTRY}/InputFiles"

    print(f"Working on {ANCESTRY}")
    
    df = pd.read_csv(f'{anno_dir}/{ANCESTRY}_CADPS2.annovar.hg38_multianno.txt', sep='\t')
    subset = df[["Chr", "Start", "End", "Ref", "Alt", "Func.refGene", "Gene.refGene", "ExonicFunc.refGene", "CLNSIG", "REVEL_score", "REVEL_rankscore", "CADD_raw", "CADD_raw_rankscore", "CADD_phred", "gnomad41_genome_fafmax_faf95_max"]]
    
    subset.to_csv(F'{anno_dir}/{ANCESTRY}_CADPS2.annovar.hg38_multianno_cropped.txt', sep='\t', index=False)
    
    print(f"{ANCESTRY} finished")

Working on FIN
FIN finished
Working on MDE
MDE finished
Working on SAS
SAS finished
Working on CAH
CAH finished

In [13]:
for GENE_NAME in GENE_DICT:
    for ANCESTRY in ANCESTRIES:
        print(f'WORKING ON: {ANCESTRY}')
        BUILD = "hg38"
        
        inputPrefix = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_{GENE_NAME}"
        # Read in ANNOVAR multianno file
        gene = pd.read_csv(f'{inputPrefix}.annovar.{BUILD}_multianno_cropped.txt', sep = '\t', header = 0)
            
        #Filter for the correct gene name (sometimes other genes are also included)
        gene['gnomad41_genome_fafmax_faf95_max'] = pd.to_numeric(gene['gnomad41_genome_fafmax_faf95_max'], errors='coerce')
        gene['CADD_phred'] = pd.to_numeric(gene['CADD_phred'], errors='coerce')
        gene['REVEL_score'] = pd.to_numeric(gene['REVEL_score'], errors='coerce')
        
            
        #Print number of variants in the different categories
        results = [] 
        
        intronic = gene[gene['Func.refGene']== 'intronic']
        upstream = gene[gene['Func.refGene']== 'upstream']
        downstream = gene[gene['Func.refGene']== 'downstream']
        utr5 = gene[gene['Func.refGene']== 'UTR5']
        utr3 = gene[gene['Func.refGene']== 'UTR3']
        splicing = gene[gene['Func.refGene']== 'splicing']
        exonic = gene[gene['Func.refGene']== 'exonic']
        stopgain = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'stopgain')]
        stoploss = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'stoploss')]
        startloss = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'startloss')]
        frameshift_deletion = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'frameshift deletion')]
        frameshift_insertion = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'frameshift insertion')]
        nonframeshift_deletion = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'nonframeshift deletion')]
        nonframeshift_insertion = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'nonframeshift insertion')]
        coding_nonsynonymous = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'nonsynonymous SNV')]
        coding_synonymous = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] == 'synonymous SNV')]
            
        #Predictors
        maf_01 = gene[gene['gnomad41_genome_fafmax_faf95_max']<0.01]
        maf_03 = gene[gene['gnomad41_genome_fafmax_faf95_max']<0.03]
        CADD_20 = gene[gene['CADD_phred']>20]
        REVEL_50 = gene[gene['REVEL_score']>0.5]
        lof = gene[(gene['Func.refGene'] == 'splicing') | (gene['ExonicFunc.refGene'] == 'stopgain') | (gene['ExonicFunc.refGene'] == 'stoploss') | (gene['ExonicFunc.refGene'] == 'startloss') | (gene['ExonicFunc.refGene'] == 'frameshift deletion') | (gene['ExonicFunc.refGene'] == 'frameshift insertion')]
        
        #CLNSIG annotation
        pathogenic =    gene[(gene['CLNSIG'] == 'Pathogenic')]
        likely_patho =  gene[(gene['CLNSIG'] == 'Likely_pathogenic')]
        var_unk_sig =   gene[(gene['CLNSIG'] == 'Uncertain_significance')]
        likely_benign = gene[(gene['CLNSIG'] == 'Likely_benign')]
        benign =        gene[(gene['CLNSIG'] == 'Benign')]
      
        variantsDict = {
                "Total variants": gene,
                "Intronic": intronic,
                "Upstream": upstream,
                "Downstream": downstream,
                "UTR3": utr3,
                "UTR5": utr5,
                "Splicing": splicing,
                "Exonic": exonic,
                "Stopgain": stopgain,
                "Stoploss": stoploss,
                "Frameshift deletion": frameshift_deletion,
                "Frameshift insertion": frameshift_insertion,
                "Non-frameshift insertion": nonframeshift_insertion,
                "Non-frameshift deletion": nonframeshift_deletion,
                "Synonymous": coding_synonymous,
                "Nonsynonymous": coding_nonsynonymous,
                "LOF": lof,
                "MAF01": maf_01,
                "MAF03": maf_03,
                "REVEL>0.5": REVEL_50,
                "CADD>20": CADD_20,
                "Pathogenic": pathogenic,
                "Likely Pathogenic": likely_patho,
                "Uncertain significance": var_unk_sig,
                "Likely Benign": likely_benign,
                "Benign": benign,
            }

                      
        variantSummary = pd.DataFrame({
                "variantType": list(variantsDict.keys()),
                "count": [len(variant) for variant in variantsDict.values()]
            })
        
        ## Save numbers of variants for future reference
        os.makedirs(f"{ANA_DIR}/{ANCESTRY}/VariantDescriptives", exist_ok = True)
        variantSummary.to_csv(f"{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}_variantCounts_refGene.csv", index=False)
       
        ## Print variants which are not "0"
        allvar = variantSummary
        allVariantSummary = variantSummary.to_string(index=False, header=False)
        filtered = variantSummary[variantSummary['count'] > 0]
        filteredVariantSummary = filtered.to_string(index=False, header=False)
        variantSummary_T = variantSummary.T.reset_index()
        variantSummary_T.columns = variantSummary_T.iloc[0]
        variantSummary_T = variantSummary_T[1:].reset_index(drop=True)
        descriptives = variantSummary_T.copy()
        descriptives.insert(0, 'Ancestry', ANCESTRY)
        descriptives.insert(1, 'Gene', GENE_NAME)
        descriptives.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}_variant_descriptives', sep="\t", index=False)
        filteredVariantSummary = filtered.to_string(index=False, header=False)                
               
        print(f"""
            =====================================
                   VARIANT SUMMARY FOR {ANCESTRY}
                   -----------------------
                   {variantSummary} 
            =====================================
                """)
            
        ## For rvtests
        ## Uncomment to_csv commands if you need to debug or full outputs
        all_variants = gene
        all_variants.to_csv(f"{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}_all_variants.csv", index=False)

        # Potential functional: These are variants annotated as frameshift, nonframeshift, startloss, stoploss, stopgain, splicing, missense, exonic, UTR5, UTR3, upstream (-100bp), downstream (+100bp), or ncRNA.
        potentially_functional = gene[gene['Func.refGene'] != 'intronic']
        potentially_functional.to_csv(f"{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}_variants_full_potentially_functional.csv", index=False)
                
        # Coding: These are variants annotated as frameshift, nonframeshift, startloss, stoploss, stopgain, splicing, or missense.
        coding_variants = gene[(gene['Func.refGene'] == 'exonic') & (gene['ExonicFunc.refGene'] != 'synonymous SNV')]
        coding_variants.to_csv(f"{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}_variants_full_coding.csv", index=False)

        potencially_pathogenic = gene[(gene['CLNSIG'] == 'Pathogenic') | (gene['CLNSIG'] == 'Likely_pathogenic') | (gene['CADD_phred']>20) | (gene['REVEL_score']>0.5)]
        potencially_pathogenic.to_csv(f"{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}_variants_potencially_pathogenic.csv", index=False)

        # Save in PLINK format
        variants_toKeep = potentially_functional[['Chr', 'Start', 'End', 'Gene.refGene']].copy()
        variants_toKeep.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.potentially_functional.variantstoKeep.txt', sep="\t", index=False, header=False)
            
        variants_toKeep2 = coding_variants[['Chr', 'Start', 'End', 'Gene.refGene']].copy()
        variants_toKeep2.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.coding_variants.variantstoKeep.txt', sep="\t", index=False, header=False)
            
        variants_toKeep4 = coding_nonsynonymous[['Chr', 'Start', 'End', 'Gene.refGene']].copy()
        variants_toKeep4.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.exonic.variantstoKeep.txt', sep="\t", index=False, header=False)
                
        variants_toKeep5 = all_variants[['Chr', 'Start', 'End', 'Gene.refGene']].copy()
        variants_toKeep5.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.all_variants.variantstoKeep.txt', sep="\t", index=False, header=False)

        variants_toKeep6 = maf_01[['Chr', 'Start', 'End', 'Gene.refGene']].copy()
        variants_toKeep6.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.maf01.variantstoKeep.txt', sep="\t", index=False, header=False)

        variants_toKeep7 = maf_03[['Chr', 'Start', 'End', 'Gene.refGene']].copy()
        variants_toKeep7.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.maf03.variantstoKeep.txt', sep="\t", index=False, header=False)

        variants_toKeep8 = lof[['Chr', 'Start', 'End', 'Gene.refGene']].copy()
        variants_toKeep8.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.lof.variantstoKeep.txt', sep="\t", index=False, header=False)

        variants_toKeep9 = potencially_pathogenic[['Chr', 'Start', 'End', 'Gene.refGene']].copy()
        variants_toKeep9.to_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.potencially_pathogenic.variantstoKeep.txt', sep="\t", index=False, header=False)

WORKING ON: AAC

            =====================================
                   VARIANT SUMMARY FOR AAC
                   -----------------------
                                    variantType  count
0             Total variants   5309
1                   Intronic   5253
2                   Upstream      1
3                 Downstream      0
4                       UTR3     16
5                       UTR5      5
6                   Splicing      0
7                     Exonic     34
8                   Stopgain      1
9                   Stoploss      0
10       Frameshift deletion      1
11      Frameshift insertion      0
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous     13
15             Nonsynonymous     19
16                       LOF      2
17                     MAF01   3578
18                     MAF03   4504
19                 REVEL>0.5      2
20                   CADD>20     16
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      2
24             Likely Benign      5
25                    Benign      5
            =====================================

WORKING ON: AFR

            =====================================
                   VARIANT SUMMARY FOR AFR
                   -----------------------
                                    variantType  count
0             Total variants   6942
1                   Intronic   6858
2                   Upstream      2
3                 Downstream      0
4                       UTR3     20
5                       UTR5     10
6                   Splicing      1
7                     Exonic     51
8                   Stopgain      2
9                   Stoploss      0
10       Frameshift deletion      1
11      Frameshift insertion      0
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous     23
15             Nonsynonymous     25
16                       LOF      4
17                     MAF01   5173
18                     MAF03   5983
19                 REVEL>0.5      2
20                   CADD>20     22
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      4
24             Likely Benign      4
25                    Benign      4
            =====================================

WORKING ON: AJ

            =====================================
                   VARIANT SUMMARY FOR AJ
                   -----------------------
                                    variantType  count
0             Total variants   2665
1                   Intronic   2633
2                   Upstream      2
3                 Downstream      0
4                       UTR3      9
5                       UTR5      6
6                   Splicing      1
7                     Exonic     14
8                   Stopgain      0
9                   Stoploss      0
10       Frameshift deletion      0
11      Frameshift insertion      0
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous      4
15             Nonsynonymous     10
16                       LOF      1
17                     MAF01   1574
18                     MAF03   1927
19                 REVEL>0.5      1
20                   CADD>20      7
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      0
24             Likely Benign      3
25                    Benign      0
            =====================================

WORKING ON: AMR

            =====================================
                   VARIANT SUMMARY FOR AMR
                   -----------------------
                                    variantType  count
0             Total variants   4720
1                   Intronic   4660
2                   Upstream      1
3                 Downstream      0
4                       UTR3     17
5                       UTR5      8
6                   Splicing      0
7                     Exonic     34
8                   Stopgain      1
9                   Stoploss      0
10       Frameshift deletion      1
11      Frameshift insertion      0
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous     11
15             Nonsynonymous     21
16                       LOF      2
17                     MAF01   2522
18                     MAF03   3422
19                 REVEL>0.5      2
20                   CADD>20     17
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      5
24             Likely Benign      4
25                    Benign      6
            =====================================

WORKING ON: CAS

            =====================================
                   VARIANT SUMMARY FOR CAS
                   -----------------------
                                    variantType  count
0             Total variants   2522
1                   Intronic   2484
2                   Upstream      2
3                 Downstream      0
4                       UTR3      7
5                       UTR5      8
6                   Splicing      0
7                     Exonic     21
8                   Stopgain      0
9                   Stoploss      0
10       Frameshift deletion      0
11      Frameshift insertion      1
12  Non-frameshift insertion      1
13   Non-frameshift deletion      0
14                Synonymous      6
15             Nonsynonymous     13
16                       LOF      1
17                     MAF01   1498
18                     MAF03   1878
19                 REVEL>0.5      2
20                   CADD>20      9
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      1
24             Likely Benign      3
25                    Benign      0
            =====================================

WORKING ON: EUR

            =====================================
                   VARIANT SUMMARY FOR EUR
                   -----------------------
                                    variantType  count
0             Total variants  11784
1                   Intronic  11632
2                   Upstream      2
3                 Downstream      5
4                       UTR3     27
5                       UTR5     20
6                   Splicing      1
7                     Exonic     97
8                   Stopgain      3
9                   Stoploss      0
10       Frameshift deletion      1
11      Frameshift insertion      1
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous     28
15             Nonsynonymous     64
16                       LOF      6
17                     MAF01   7923
18                     MAF03   8648
19                 REVEL>0.5     12
20                   CADD>20     53
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance     19
24             Likely Benign      6
25                    Benign      2
            =====================================

WORKING ON: EAS

            =====================================
                   VARIANT SUMMARY FOR EAS
                   -----------------------
                                    variantType  count
0             Total variants   2680
1                   Intronic   2636
2                   Upstream      1
3                 Downstream      1
4                       UTR3      8
5                       UTR5     11
6                   Splicing      0
7                     Exonic     23
8                   Stopgain      0
9                   Stoploss      0
10       Frameshift deletion      1
11      Frameshift insertion      1
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous     11
15             Nonsynonymous     10
16                       LOF      2
17                     MAF01   1844
18                     MAF03   2009
19                 REVEL>0.5      1
20                   CADD>20      7
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      0
24             Likely Benign      1
25                    Benign      0
            =====================================

WORKING ON: FIN

            =====================================
                   VARIANT SUMMARY FOR FIN
                   -----------------------
                                    variantType  count
0             Total variants    637
1                   Intronic    631
2                   Upstream      0
3                 Downstream      0
4                       UTR3      1
5                       UTR5      2
6                   Splicing      0
7                     Exonic      3
8                   Stopgain      0
9                   Stoploss      0
10       Frameshift deletion      0
11      Frameshift insertion      0
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous      1
15             Nonsynonymous      2
16                       LOF      0
17                     MAF01    199
18                     MAF03    414
19                 REVEL>0.5      1
20                   CADD>20      2
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      0
24             Likely Benign      1
25                    Benign      0
            =====================================

WORKING ON: MDE

            =====================================
                   VARIANT SUMMARY FOR MDE
                   -----------------------
                                    variantType  count
0             Total variants   2467
1                   Intronic   2439
2                   Upstream      1
3                 Downstream      1
4                       UTR3      6
5                       UTR5      4
6                   Splicing      0
7                     Exonic     16
8                   Stopgain      0
9                   Stoploss      0
10       Frameshift deletion      0
11      Frameshift insertion      0
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous      5
15             Nonsynonymous     11
16                       LOF      0
17                     MAF01   1124
18                     MAF03   1516
19                 REVEL>0.5      1
20                   CADD>20      8
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      2
24             Likely Benign      3
25                    Benign      1
            =====================================

WORKING ON: SAS

            =====================================
                   VARIANT SUMMARY FOR SAS
                   -----------------------
                                    variantType  count
0             Total variants   2039
1                   Intronic   2008
2                   Upstream      0
3                 Downstream      0
4                       UTR3      8
5                       UTR5      6
6                   Splicing      0
7                     Exonic     17
8                   Stopgain      0
9                   Stoploss      0
10       Frameshift deletion      0
11      Frameshift insertion      0
12  Non-frameshift insertion      1
13   Non-frameshift deletion      0
14                Synonymous      9
15             Nonsynonymous      7
16                       LOF      0
17                     MAF01   1182
18                     MAF03   1460
19                 REVEL>0.5      2
20                   CADD>20      4
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      2
24             Likely Benign      0
25                    Benign      0
            =====================================

WORKING ON: CAH

            =====================================
                   VARIANT SUMMARY FOR CAH
                   -----------------------
                                    variantType  count
0             Total variants   5361
1                   Intronic   5291
2                   Upstream      1
3                 Downstream      0
4                       UTR3     21
5                       UTR5     10
6                   Splicing      0
7                     Exonic     38
8                   Stopgain      1
9                   Stoploss      0
10       Frameshift deletion      0
11      Frameshift insertion      0
12  Non-frameshift insertion      0
13   Non-frameshift deletion      0
14                Synonymous     16
15             Nonsynonymous     21
16                       LOF      1
17                     MAF01   2993
18                     MAF03   4080
19                 REVEL>0.5      2
20                   CADD>20     15
21                Pathogenic      0
22         Likely Pathogenic      0
23    Uncertain significance      1
24             Likely Benign      7
25                    Benign      6
            =====================================

In [14]:
all_variant_stats = []
patho_variant_stats = []
for GENE_NAME in GENE_DICT:
        for ANCESTRY in ANCESTRIES:
            descriptives = pd.read_csv(f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}_variant_descriptives', sep="\t", header=0)
            all_variant_stats.append(descriptives)
all_variant_stats = pd.concat(all_variant_stats)
all_variant_stats.to_csv(f'{RESU_DIR}/{analysis}/CADPS2_{analysis}_AllVariantsStats.csv', index=False)

## Burden Analyses using RVTests

In [13]:
#Burden tests are performed in three groups: maf < 0.01, maf < 0.03 and potencially pathogenic.

burden_class = ['maf01', 'maf03', 'potencially_pathogenic']
for i in burden_class:  
    print(i)

maf01
maf03
potencially_pathogenic

In [25]:
## Extract variants of interest as vcf

def burdenPrep(GENE_NAME, ANCESTRY, burden_class):

    ## Input files
    inputRawPFILE = f"{IMPUTED_GENO_PATH}/{ANCESTRY}/chr7_{ANCESTRY}_release11_vwb"
    samplesToKeep = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}.samplestokeep"
    variantsToKeep = f"{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.{burden_class}.variantstoKeep.txt"
    outputVCF = f"{ANA_DIR}/{ANCESTRY}/Burden/{ANCESTRY}_{GENE_NAME}.{burden_class}"
    
    ## Define plink2 command for extraction
    variantExtractor = [
        f"{TOOL_DIR}/plink2",
        "--pfile", inputRawPFILE,
        "--keep", samplesToKeep,
        "--extract", "range", variantsToKeep,
        "--recode", "vcf-iid",
        "--out", outputVCF
    ]

        ## Run plink2 command as bash subprocess
    subprocess.run(variantExtractor, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)
    vcfGzip = [
        "bgzip",
        "-f", f"{outputVCF}.vcf"
        ]

        ## Run plink2 command as bash subprocess
    subprocess.run(vcfGzip, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)
    vcfIndex = [
        "tabix",
        "-f", "-p", "vcf", f"{outputVCF}.vcf.gz"      
        ]    
    ## Run plink2 command as bash subprocess
    subprocess.run(vcfIndex, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)

In [27]:
for ancestry in ANCESTRIES:
    print(f'WORKING ON: {ancestry}\n')
    for burden in burden_class: 
        print(f'\tClass: {burden}')
        try:
            burdenPrep("CADPS2", ancestry, burden)
            print(f'\t{ancestry}, {burden} - DONE\n')
        except Exception as e:
            print(f'{ancestry}, {burden} - FAIL\n')

WORKING ON: AAC

	Class: maf01
	AAC, maf01 - DONE

	Class: maf03
	AAC, maf03 - DONE

	Class: potencially_pathogenic
	AAC, potencially_pathogenic - DONE

WORKING ON: AFR

	Class: maf01
	AFR, maf01 - DONE

	Class: maf03
	AFR, maf03 - DONE

	Class: potencially_pathogenic
	AFR, potencially_pathogenic - DONE

WORKING ON: AJ

	Class: maf01
	AJ, maf01 - DONE

	Class: maf03
	AJ, maf03 - DONE

	Class: potencially_pathogenic
	AJ, potencially_pathogenic - DONE

WORKING ON: AMR

	Class: maf01
	AMR, maf01 - DONE

	Class: maf03
	AMR, maf03 - DONE

	Class: potencially_pathogenic
	AMR, potencially_pathogenic - DONE

WORKING ON: CAS

	Class: maf01
	CAS, maf01 - DONE

	Class: maf03
	CAS, maf03 - DONE

	Class: potencially_pathogenic
	CAS, potencially_pathogenic - DONE

WORKING ON: EUR

	Class: maf01
	EUR, maf01 - DONE

	Class: maf03
	EUR, maf03 - DONE

	Class: potencially_pathogenic
	EUR, potencially_pathogenic - DONE

WORKING ON: EAS

	Class: maf01
	EAS, maf01 - DONE

	Class: maf03
	EAS, maf03 - DONE

	Class: potencially_pathogenic
	EAS, potencially_pathogenic - DONE

WORKING ON: FIN

	Class: maf01
	FIN, maf01 - DONE

	Class: maf03
	FIN, maf03 - DONE

	Class: potencially_pathogenic
	FIN, potencially_pathogenic - DONE

WORKING ON: MDE

	Class: maf01
	MDE, maf01 - DONE

	Class: maf03
	MDE, maf03 - DONE

	Class: potencially_pathogenic
	MDE, potencially_pathogenic - DONE

WORKING ON: SAS

	Class: maf01
	SAS, maf01 - DONE

	Class: maf03
	SAS, maf03 - DONE

	Class: potencially_pathogenic
	SAS, potencially_pathogenic - DONE

WORKING ON: CAH

	Class: maf01
	CAH, maf01 - DONE

	Class: maf03
	CAH, maf03 - DONE

	Class: potencially_pathogenic
	CAH, potencially_pathogenic - DONE

In [14]:
## Run burden test with RVtests

def burdenRVTests(GENE_NAME, ANCESTRY, burden_class):
   
    ## Get ANCESTRY name
    inputVCF = f"{ANA_DIR}/{ANCESTRY}/Burden/{ANCESTRY}_{GENE_NAME}.{burden_class}.vcf.gz"
    outputBURDEN = f"{ANA_DIR}/{ANCESTRY}/Burden/{ANCESTRY}_{GENE_NAME}_{burden_class}.burden"
    covariate = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_covariate_file.txt"
    refFlat = f"{TOOL_DIR}/refFlat_HG38_all_chr.txt"
    
    burdenRVTests = [
        #RVtests with covariates 
        #Make sure the pheno and covariate file starts with the first 5 columsn: fid, iid, fatid, matid, sex
        #The pheno-name flag only works when the pheno/covar file is structured properly
        f"{TOOL_DIR}/rvtests/executable/rvtest", 
        "--noweb", 
        "--hide-covar",
        "--out", outputBURDEN,
        "--kernel", "skat,skato",
        "--inVcf", inputVCF,
        "--pheno", covariate,
        "--pheno-name", "PHENO",
        "--gene", GENE_NAME,
        "--geneFile", refFlat,
        "--covar", covariate,
        "--covar-name", "SEX,AGE,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10",
    ]
    
    ## Run plink2 command as bash subprocess
    subprocess.run(burdenRVTests, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)

In [ ]:
refFlat = f"{TOOL_DIR}/refFlat_HG38_all_chr.txt"
for ancestry in ANCESTRIES:
    print(f'WORKING ON: {ancestry}\n')
    for burden in burden_class: 
        print(f'\tClass: {burden}')
        try:
            burdenRVTests("CADPS2", ancestry, burden)
            print(f'\t{ancestry}, {burden} - DONE\n')
        except Exception as e:
            print(f'{ancestry}, {burden} - FAIL: {e}\n')

WORKING ON: EUR

	Class: maf01

In [14]:
skat_df = []
skatO_df = []

for GENE_NAME in GENE_DICT:
    for ANCESTRY in ANCESTRIES:
        for cls in burden_class:
        
            path_skat = Path(f"{ANA_DIR}/{ANCESTRY}/Burden/{ANCESTRY}_{GENE_NAME}_{cls}.burden.Skat.assoc")
            path_skatO = Path(f"{ANA_DIR}/{ANCESTRY}/Burden/{ANCESTRY}_{GENE_NAME}_{cls}.burden.SkatO.assoc")            
            
            try:
                if path_skat.is_file():
                    df = pd.read_csv(path_skat, sep="\t")
                    df.insert(0, "ANCESTRY", ANCESTRY)
                    df.insert(1, "GENE", GENE_NAME)
                    df.insert(2, "CLASS", cls)
                    skat_df.append(df)
            except:
                pass
            
            try:
                if path_skatO.is_file():
                    df = pd.read_csv(path_skatO, sep="\t")
                    df.insert(0, "ANCESTRY", ANCESTRY)
                    df.insert(1, "GENE", GENE_NAME)
                    df.insert(2, "CLASS", cls)
                    skatO_df.append(df)
            except:
                pass

In [15]:
skat_df = pd.concat(skat_df, ignore_index=True) if skat_df else pd.DataFrame()
skatO_df = pd.concat(skatO_df, ignore_index=True) if skatO_df else pd.DataFrame()

In [16]:
skat_df

,ANCESTRY,GENE,CLASS,Gene,RANGE,N_INFORMATIVE,NumVar,NumPolyVar,Q,Pvalue,NumPerm,ActualPerm,Stat,NumGreater,NumEqual,PermPvalue
0,AAC,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1178,3408,3343,1.970880e+06,0.570715,10000,1598,1.970880e+06,1000,0,0.625782
1,AAC,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1178,4298,4229,4.717270e+06,0.242942,10000,4052,4.717270e+06,1000,0,0.246792
2,AAC,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1178,16,16,1.502670e+04,0.183620,10000,4740,1.502670e+04,1000,0,0.210970
3,AFR,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",6504,4950,4902,1.412050e+07,0.456168,10000,2118,1.412050e+07,1000,0,0.472144
4,AFR,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",6504,5732,5676,2.968870e+07,0.528860,10000,1751,2.968870e+07,1000,0,0.571102
5,AFR,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",6504,22,22,4.718570e+04,0.667842,10000,1537,4.718570e+04,1000,0,0.650618
6,AJ,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1868,1484,1395,1.069670e+06,0.722846,10000,1312,1.069670e+06,1000,0,0.762195
7,AJ,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1868,1822,1724,1.535850e+06,0.764162,10000,1269,1.535850e+06,1000,0,0.788022
8,AJ,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1868,7,7,2.371640e+03,0.558081,10000,1770,2.371640e+03,1000,0,0.564972
9,AMR,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",3325,2429,2382,1.349010e+06,0.851333,10000,1133,1.349010e+06,1000,0,0.882613
10,AMR,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",3325,3299,3248,3.201820e+06,0.539162,10000,1678,3.201820e+06,1000,0,0.595948
11,AMR,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",3325,18,17,3.831030e+04,0.380819,10000,2527,3.831030e+04,1000,0,0.395726
12,CAS,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1301,1438,1200,6.140460e+05,0.166298,10000,4075,6.140460e+05,1000,0,0.245399
13,CAS,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1301,1799,1557,1.147010e+06,0.675382,10000,1277,1.147010e+06,1000,0,0.783085
14,CAS,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1301,9,9,1.490620e+04,0.056096,10000,10000,1.490620e+04,510,0,0.051000
15,EAS,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",4487,1743,1688,2.093430e+06,0.348702,10000,2813,2.093430e+06,1000,0,0.355492
16,EAS,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",4487,1906,1847,3.382080e+06,0.684347,10000,1408,3.382080e+06,1000,0,0.710227
17,EAS,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",4487,7,7,1.364130e+03,0.937988,10000,1057,1.364130e+03,1000,0,0.946074
18,EUR,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",37790,7727,7239,5.203000e+07,0.120687,10000,8241,5.203000e+07,1000,0,0.121344
19,EUR,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",37790,8428,7932,8.573400e+07,0.114104,10000,8417,8.573400e+07,1000,0,0.118807
20,EUR,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",37790,55,49,9.398160e+04,0.965045,10000,1037,9.398160e+04,1000,0,0.964320
21,FIN,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",59,194,125,3.148260e+03,0.112984,10000,1800,3.148260e+03,1000,0,0.555556
22,FIN,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",59,399,302,1.252290e+04,0.121960,10000,2724,1.252290e+04,1000,0,0.367107
23,FIN,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",59,2,2,8.637650e+01,0.096364,10000,2735,8.637650e+01,1000,0,0.365631
24,MDE,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1405,1080,1005,9.895920e+05,0.030920,10000,10000,9.895920e+05,754,0,0.075400
25,MDE,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1405,1452,1356,1.713580e+06,0.037159,10000,10000,1.713580e+06,949,0,0.094900
26,MDE,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1405,8,7,2.322680e+03,0.783851,10000,1212,2.322680e+03,1000,0,0.825083
27,SAS,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",655,1119,984,5.146450e+05,0.035615,10000,10000,5.146450e+05,380,0,0.038000
28,SAS,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",655,1377,1237,8.281280e+05,0.111985,10000,8361,8.281280e+05,1000,0,0.119603
29,SAS,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",655,4,3,3.478550e+03,0.168871,10000,5776,3.478550e+03,1000,0,0.173130
30,CAH,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",971,2850,2771,1.265720e+06,0.182560,10000,5619,1.265720e+06,1000,0,0.177968
31,CAH,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",971,3888,3797,2.194340e+06,0.402879,10000,2032,2.194340e+06,1000,0,0.492126
32,CAH,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",971,15,14,6.970470e+03,0.399211,10000,2229,6.970470e+03,1000,0,0.448632

In [17]:
skatO_df

,ANCESTRY,GENE,CLASS,Gene,RANGE,N_INFORMATIVE,NumVar,NumPolyVar,Q,rho,Pvalue
0,AAC,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1178,3408,3343,5.876050e+07,1.0,0.156816
1,AAC,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1178,4298,4229,2.038630e+07,0.1,0.125826
2,AAC,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1178,16,16,2.348090e+04,1.0,0.069439
3,AFR,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",6504,4950,4902,7.060250e+06,0.0,0.673830
4,AFR,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",6504,5732,5676,3.970740e+08,1.0,0.516480
5,AFR,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",6504,22,22,3.589250e+04,1.0,0.497383
6,AJ,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1868,1484,1395,1.403840e+06,1.0,0.519768
7,AJ,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1868,1822,1724,7.434410e+06,1.0,0.159639
8,AJ,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1868,7,7,1.303330e+03,1.0,0.537736
9,AMR,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",3325,2429,2382,8.924940e+06,1.0,0.234360
10,AMR,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",3325,3299,3248,2.855830e+07,1.0,0.231934
11,AMR,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",3325,18,17,1.915520e+04,0.0,0.507051
12,CAS,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1301,1438,1200,3.070230e+05,0.0,0.300933
13,CAS,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1301,1799,1557,8.928140e+05,1.0,0.766962
14,CAS,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1301,9,9,7.453080e+03,0.0,0.102978
15,EAS,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",4487,1743,1688,1.046720e+06,0.0,0.539213
16,EAS,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",4487,1906,1847,1.691040e+06,0.0,0.886035
17,EAS,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",4487,7,7,3.673220e+02,1.0,0.869824
18,EUR,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",37790,7727,7239,2.601510e+07,0.0,0.230715
19,EUR,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",37790,8428,7932,4.286700e+07,0.0,0.208982
20,EUR,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",37790,55,49,4.808350e+04,1.0,0.810320
21,FIN,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",59,194,125,1.574130e+03,0.0,0.209029
22,FIN,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",59,399,302,1.819750e+04,0.2,0.108510
23,FIN,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",59,2,2,4.318820e+01,0.0,0.099953
24,MDE,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1405,1080,1005,4.947960e+05,0.0,0.060753
25,MDE,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1405,1452,1356,3.424320e+06,0.1,0.024633
26,MDE,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",1405,8,7,7.310230e+02,1.0,0.796736
27,SAS,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",655,1119,984,2.573230e+05,0.0,0.074529
28,SAS,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",655,1377,1237,4.140640e+05,0.0,0.211325
29,SAS,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",655,4,3,2.451590e+03,1.0,0.152094
30,CAH,CADPS2,maf01,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",971,2850,2771,6.328590e+05,0.0,0.312137
31,CAH,CADPS2,maf03,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",971,3888,3797,1.097170e+06,0.0,0.598281
32,CAH,CADPS2,potencially_pathogenic,CADPS2,"7:122318423-122886460,7:122318423-122886460,7:...",971,15,14,6.459350e+03,1.0,0.310440

In [18]:
skat_df.to_csv(f"{RESU_DIR}/{analysis}/CADPS2.{analysis}_BURDEN.SKAT.tsv", sep='\t', index=False)
skatO_df.to_csv(f"{RESU_DIR}/{analysis}/CADPS2.{analysis}_BURDEN.SKAT-O.tsv", sep='\t', index=False)

## Case/Control Analysis

### Glossary

- CHR Chromosome code
- SNP Variant identifier
- A1 Allele 1 (usually minor)
- A2 Allele 2 (usually major)
- MAF Allele 1 frequency in all subjects
- F_A/MAF_A Allele 1 frequency in cases
- F_U/MAF_U Allele 1 frequency in controls
- NCHROBS_A Number of case allele observations
- NCHROBS_U Number of control allele observations

## ALL VARIANTS

#### assoc

In [89]:
ANCESTRIES = ['AAC', 'AFR', 'AJ', 'AMR', 'CAS', 'EAS', 'EUR', 'FIN', 'MDE', 'SAS', 'CAH']

for anc in ANCESTRIES:
    print(f"Working on {anc}")
    
    inputpfile = f"{ANA_DIR}/{anc}/InputFiles/{anc}_CADPS2"
    outbfile = f"{ANA_DIR}/{anc}/InputFiles/{anc}_CADPS2"
    
    makebfiles = [
        f"{TOOL_DIR}/plink2",
          "--pfile", inputpfile,
          "--make-bed",
          "--out", outbfile
    ]
    
    subprocess.run(makebfiles, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)

    print(f"{anc} done, saved in {ANA_DIR}/{anc}/InputFiles/{anc}_CADPS2")

Working on AAC
AAC done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/InputFiles/AAC_CADPS2
Working on AFR
AFR done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/InputFiles/AFR_CADPS2
Working on AJ
AJ done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/InputFiles/AJ_CADPS2
Working on AMR
AMR done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/InputFiles/AMR_CADPS2
Working on CAS
CAS done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/InputFiles/CAS_CADPS2
Working on EAS
EAS done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/InputFiles/EAS_CADPS2
Working on EUR
EUR done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EUR/InputFiles/EUR_CADPS2
Working on FIN
FIN done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/InputFiles/FIN_CADPS2
Working on MDE
MDE done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/InputFiles/MDE_CADPS2
Working on SAS
SAS done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/InputFiles/SAS_CADPS2
Working on CAH
CAH done, saved in /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/InputFiles/CAH_CADPS2

In [90]:
## extract region using plink

def variantAssoc(ANCESTRY):
    
    ## Analysis start time
    ts_start = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   ASSOCIATION START:   {ts_start}   =====================\n")
    
    ## Get ANCESTRY name
    print(f"Association test for {GENE_NAME} from {ANCESTRY} NBA Release 11 data.")

    samplesToKeep = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}.samplestokeep"
    inputbfile = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_{GENE_NAME}"
    outputAssoc = f"{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_{GENE_NAME}.assoc.allVariants"
    outputRaw = f"{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_{GENE_NAME}.raw.allVariants"
    covariate = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_covariate_file.txt"

    os.makedirs(f"{ANA_DIR}/{ANCESTRY}/Association", exist_ok = True)

    plinkAssoc = [
        f"{TOOL_DIR}/plink1.9",
        "--bfile", inputbfile,
        "--keep", samplesToKeep,
        "--assoc",
        "--maf", "0.01",
        "--mac", "2",
        "--hwe", "0.0001",
        "--adjust",
        "--ci", "0.95",
        "--out", outputAssoc
    ]

    subprocess.run(plinkAssoc, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)

    recodeA = [
            f"{TOOL_DIR}/plink1.9",
            "--bfile", inputbfile,
            "--keep", samplesToKeep,
            "--recode", "A",
            "--out", outputRaw
        ]

    subprocess.run(recodeA, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)
    
    ## Analysis end time
    ts_finish = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   ASSOCIATION END:   {ts_finish}   =====================\n")
    
    ## Return ANCESTRY, position and gene
    return f"Test performed on: {ANCESTRY} in {GENE_NAME}"

In [91]:
for ances in ANCESTRIES:
    variantAssoc(ances)

=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-32-44   =====================

Association test for CADPS2 from AAC NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-32-46   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-32-46   =====================

Association test for CADPS2 from AFR NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-32-51   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-32-51   =====================

Association test for CADPS2 from AJ NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-32-54   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-32-54   =====================

Association test for CADPS2 from AMR NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-32-57   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-32-57   =====================

Association test for CADPS2 from CAS NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-32-59   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-32-59   =====================

Association test for CADPS2 from EAS NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-33-02   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-33-02   =====================

Association test for CADPS2 from EUR NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-33-46   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-33-46   =====================

Association test for CADPS2 from FIN NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-33-47   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-33-47   =====================

Association test for CADPS2 from MDE NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-33-49   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-33-49   =====================

Association test for CADPS2 from SAS NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-33-51   =====================



=============   ASSOCIATION START:   Date: 2026-02-25   Time: 19-33-51   =====================

Association test for CADPS2 from CAH NBA Release 11 data.


=============   ASSOCIATION END:   Date: 2026-02-25   Time: 19-33-52   =====================

In [ ]:
#Process results from plink assoc unadjusted analysis for CODING variants
#As there are very few or no significant variants with p-value < 0.05 - we will save results dataframe of all coding variants

for ANCESTRY in ANCESTRIES:
    ## Input files
    outputAssoc = f"{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_{GENE_NAME}.assoc.allVariants"
    outputRaw = f"{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_{GENE_NAME}.raw.allVariants"

    #Look at assoc results
    freq = pd.read_csv(f'{outputAssoc}.assoc', sep='\s+')
    
    #Filter for significant variants p < 0.05 - if any
    sig_all_nonadj = freq[freq['P']<0.05]
    
    print(f'There are {len(sig_all_nonadj)} variants with p-value < 0.05')

    #Read in plink recoded data (.raw file)
    recode = pd.read_csv(f'{outputRaw}.raw', sep='\s+')

    # Make a list from the column names
    column_names = recode.columns.tolist()

    # Drop the first 6 columns to keep the variants 
    variants = column_names[6:]

    print(f'Number of variants in {ANCESTRY} for {GENE_NAME}: {len(variants)}')

    # Pre-filter the dataset
    cases_data = recode[recode['PHENOTYPE'] == 2]
    controls_data = recode[recode['PHENOTYPE'] == 1]

    results = []

    # Pre-filter the dataset
    total_cases = cases_data.shape[0]
    total_controls = controls_data.shape[0]
    results = []

    for variant in variants:
        ## For PD cases
        hom_cases = (cases_data[variant] == 2).sum()
        het_cases = (cases_data[variant] == 1).sum()
        hom_ref_cases = (cases_data[variant] == 0).sum()  # Homozygous reference genotype
        missing_cases = total_cases - (hom_cases + het_cases + hom_ref_cases)  # Missing data count
        freq_cases = (2 * hom_cases + het_cases) / (2 * (total_cases - missing_cases))  # Adjust for missing data in denominator

        ## For controls
        hom_controls = (controls_data[variant] == 2).sum()
        het_controls = (controls_data[variant] == 1).sum()
        hom_ref_controls = (controls_data[variant] == 0).sum()  # Homozygous reference genotype
        missing_controls = total_controls - (hom_controls + het_controls + hom_ref_controls)  # Missing data count
        freq_controls = (2 * hom_controls + het_controls) / (2 * (total_controls - missing_controls))  # Adjust for missing data in denominator
    
        # Append results in dictionary format
        results.append({
            'Variant': variant,
            'Hom Cases': hom_cases,
            'Het Cases': het_cases,
            'Hom Ref Cases': hom_ref_cases,
            'Missing Cases': missing_cases,
            'Total Cases': total_cases,
            'Carrier Freq in Cases': freq_cases,
            'Hom Controls': hom_controls,
            'Het Controls': het_controls,
            'Hom Ref Controls': hom_ref_controls,
            'Missing Controls': missing_controls,
            'Total Controls': total_controls,
            'Carrier Freq in Controls': freq_controls
        })

    # Return
    df_results = pd.DataFrame(results)
    df_results['SNP'] = df_results['Variant'].apply(lambda x: x.rsplit('_', 1)[0])

    #Print dimensions of the df_results dataframe
    print(f'df_results shape: {df_results.shape}')
          
    #Merge with the assoc file
    sig_merge = freq[['SNP','A1','F_A','F_U','A2','L95','OR', 'SE', 'U95','P']]
    merged = pd.merge(df_results, sig_merge, on='SNP', how='right')
    
    #Print dimensions of the merged dataframe (just adding more columns)
    print(f'Merged dataframe shape: {merged.shape}\n\n') 
    
    ## Save to CSV
    merged.to_csv(f'{ANA_DIR}/{ANCESTRY}/{ANCESTRY}_{GENE_NAME}.assoc.allVariants.txt', sep = '\t', index=False)

There are 84 variants with p-value < 0.05
Number of variants in AAC for CADPS2: 5309
df_results shape: (5309, 14)
Merged dataframe shape: (1178, 23)


There are 21 variants with p-value < 0.05
Number of variants in AFR for CADPS2: 6942
df_results shape: (6942, 14)
Merged dataframe shape: (1059, 23)


There are 17 variants with p-value < 0.05
Number of variants in AJ for CADPS2: 2665
df_results shape: (2665, 14)
Merged dataframe shape: (510, 23)


There are 308 variants with p-value < 0.05
Number of variants in AMR for CADPS2: 4720
df_results shape: (4720, 14)
Merged dataframe shape: (423, 23)


There are 31 variants with p-value < 0.05
Number of variants in CAS for CADPS2: 2522
df_results shape: (2522, 14)
Merged dataframe shape: (398, 23)


There are 69 variants with p-value < 0.05
Number of variants in EAS for CADPS2: 2680
df_results shape: (2680, 14)
Merged dataframe shape: (365, 23)


There are 67 variants with p-value < 0.05

#### GLM

In [14]:
## extract region using plink

def variantGLM(ANCESTRY):
    
    ## Analysis start time
    ts_start = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   GLM START:   {ts_start}   =====================\n")
    
    ## Get ANCESTRY name
    print(f"GLM test for {GENE_NAME} from {ANCESTRY} NBA Release 11 data.")

    inputpfile = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_{GENE_NAME}"
    outputGLM = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_{GENE_NAME}.glm.allVariants"
    outputRaw = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_{GENE_NAME}.raw.allVariants"
    samplesToKeep = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}.samplestokeep"
    covariate = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_covariate_file.txt"
    # Print the command to be executed (for debugging purposes)
    print(f'Running Plink2 GLM for ANCESTRY: {ANCESTRY}')
    
    ## Define plink2 command for extraction
    plinkGLM = [
        f"{TOOL_DIR}/plink2",
        "--pfile", inputpfile,
        "--keep", samplesToKeep,
        "--glm",
        "--maf", "0.01",
        "--mac", "2",
        "--hwe", "0.0001", "keep-fewhet",
        "--adjust",
        "--allow-no-sex",
        "--ci", "0.95",
        "--covar", covariate,
        "--covar-variance-standardize",
        "--covar-name", "SEX,AGE,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10",
        "--out", outputGLM
    ]

    ## Run plink2 command as bash subprocess
    subprocess.run(plinkGLM, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)

    recodeA = [
            f"{TOOL_DIR}/plink2",
            "--pfile", inputpfile,
            "--keep", samplesToKeep,
            "--recode", "A",
            "--out", outputRaw
        ]

    subprocess.run(recodeA, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)
    
    ## Analysis end time
    ts_finish = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   GLM END:   {ts_finish}   =====================\n")
    
    ## Return ANCESTRY, position and gene
    return f"GLM test performed on: {ANCESTRY} in {GENE_NAME}"

In [15]:
for anc in ANCESTRIES:
    os.makedirs(f"{ANA_DIR}/{anc}/GLM", exist_ok = True)
    variantGLM(anc)

=============   GLM START:   Date: 2026-02-25   Time: 16-51-37   =====================

GLM test for CADPS2 from AAC NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: AAC


=============   GLM END:   Date: 2026-02-25   Time: 16-51-40   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-51-40   =====================

GLM test for CADPS2 from AFR NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: AFR


=============   GLM END:   Date: 2026-02-25   Time: 16-51-46   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-51-46   =====================

GLM test for CADPS2 from AJ NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: AJ


=============   GLM END:   Date: 2026-02-25   Time: 16-51-48   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-51-48   =====================

GLM test for CADPS2 from AMR NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: AMR


=============   GLM END:   Date: 2026-02-25   Time: 16-51-51   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-51-51   =====================

GLM test for CADPS2 from CAS NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: CAS


=============   GLM END:   Date: 2026-02-25   Time: 16-51-54   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-51-54   =====================

GLM test for CADPS2 from EAS NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: EAS


=============   GLM END:   Date: 2026-02-25   Time: 16-51-57   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-51-57   =====================

GLM test for CADPS2 from EUR NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: EUR


=============   GLM END:   Date: 2026-02-25   Time: 16-52-45   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-52-45   =====================

GLM test for CADPS2 from FIN NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: FIN


=============   GLM END:   Date: 2026-02-25   Time: 16-52-46   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-52-46   =====================

GLM test for CADPS2 from MDE NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: MDE


=============   GLM END:   Date: 2026-02-25   Time: 16-52-48   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-52-48   =====================

GLM test for CADPS2 from SAS NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: SAS


=============   GLM END:   Date: 2026-02-25   Time: 16-52-50   =====================



=============   GLM START:   Date: 2026-02-25   Time: 16-52-50   =====================

GLM test for CADPS2 from CAH NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: CAH


=============   GLM END:   Date: 2026-02-25   Time: 16-52-52   =====================

In [22]:
for ANCESTRY in ANCESTRIES:
    try:
        glm_file = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_CADPS2.glm.allVariants.PHENO1.glm.logistic.hybrid"
        df = pd.read_csv(glm_file, sep='\t') 
        df = df.rename(columns={'LOG(OR)_SE': 'SE'})
        df.to_csv(glm_file, sep='\t', index=False)
    except:
        pass

In [12]:
#Process results from plink glm analysis for ALL variants
#As there are very few or no significant variants with p-value < 0.05 - we will save results dataframe of all coding variants

for ANCESTRY in ANCESTRIES:
    print(f'WORKING ON: {ANCESTRY}')    
    try:
        glm_file = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_{GENE_NAME}.glm.allVariants.PHENO1.glm.logistic.hybrid"
        raw_file = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_{GENE_NAME}.raw.allVariants.raw"

        glm = pd.read_csv(glm_file, sep='\s+')
        glm_add = glm[glm['TEST']=="ADD"]
        
        #Filter for significant variants p < 0.05 - if any
        significant = glm_add[glm_add['P']<0.05]
        print(f'There are {len(significant)} variants with p-value < 0.05 in glm')
        
        #Read in plink recoded data (.raw file)
        recode = pd.read_csv(raw_file, sep='\s+')
    
        # Make a list from the column names
        column_names = recode.columns.tolist()
    
        # Drop the first 6 columns to keep the variants 
        variants = column_names[6:]
    
        print(f'Number of variants in {ANCESTRY} for {GENE_NAME}: {len(variants)}')
    
        # Pre-filter the dataset
        cases_data = recode[recode['PHENOTYPE'] == 2]
        controls_data = recode[recode['PHENOTYPE'] == 1]
    
        results = []
    
        # Pre-filter the dataset
        total_cases = cases_data.shape[0]
        total_controls = controls_data.shape[0]
        results = []
    
        for variant in variants:
            ## For PD cases
            hom_cases = (cases_data[variant] == 2).sum()
            het_cases = (cases_data[variant] == 1).sum()
            hom_ref_cases = (cases_data[variant] == 0).sum()  # Homozygous reference genotype
            missing_cases = total_cases - (hom_cases + het_cases + hom_ref_cases)  # Missing data count
            freq_cases = (2 * hom_cases + het_cases) / (2 * (total_cases - missing_cases))  # Adjust for missing data in denominator
    
            ## For controls
            hom_controls = (controls_data[variant] == 2).sum()
            het_controls = (controls_data[variant] == 1).sum()
            hom_ref_controls = (controls_data[variant] == 0).sum()  # Homozygous reference genotype
            missing_controls = total_controls - (hom_controls + het_controls + hom_ref_controls)  # Missing data count
            freq_controls = (2 * hom_controls + het_controls) / (2 * (total_controls - missing_controls))  # Adjust for missing data in denominator
        
            # Append results in dictionary format
            results.append({
                'Variant': variant,
                'Hom Cases': hom_cases,
                'Het Cases': het_cases,
                'Hom Ref Cases': hom_ref_cases,
                'Missing Cases': missing_cases,
                'Total Cases': total_cases,
                'Carrier Freq in Cases': freq_cases,
                'Hom Controls': hom_controls,
                'Het Controls': het_controls,
                'Hom Ref Controls': hom_ref_controls,
                'Missing Controls': missing_controls,
                'Total Controls': total_controls,
                'Carrier Freq in Controls': freq_controls
            })
    
        # Return
        df_results = pd.DataFrame(results)
        df_results['ID'] = df_results['Variant'].apply(lambda x: x.rsplit('_', 1)[0])
    
        #Print dimensions of the df_results dataframe
        print(f'df_results shape: {df_results.shape}')
        
        #Merge with the glm file
        sig_merge = glm_add[['ID','A1','A1_FREQ','OBS_CT','OR','SE','Z_STAT','P']]
        merged = pd.merge(df_results, sig_merge, on='ID', how='right')
        
        #Print dimensions of the merged dataframe (just adding more columns)
        print(f'Merged dataframe shape: {merged.shape}\n\n')

        ## Save to CSV
        merged.to_csv(f'{ANA_DIR}/{ANCESTRY}/{ANCESTRY}_{GENE_NAME}.glm.allVariants.txt', sep = '\t', index=False)
    except Exception as error:
        print(error)
        pass

WORKING ON: AAC
There are 53 variants with p-value < 0.05 in glm
Number of variants in AAC for CADPS2: 5309
df_results shape: (5309, 14)
Merged dataframe shape: (1203, 21)


WORKING ON: AFR
There are 38 variants with p-value < 0.05 in glm
Number of variants in AFR for CADPS2: 6942
df_results shape: (6942, 14)
Merged dataframe shape: (1120, 21)


WORKING ON: AJ
There are 6 variants with p-value < 0.05 in glm
Number of variants in AJ for CADPS2: 2665
df_results shape: (2665, 14)
Merged dataframe shape: (519, 21)


WORKING ON: AMR
There are 36 variants with p-value < 0.05 in glm
Number of variants in AMR for CADPS2: 4720
df_results shape: (4720, 14)
Merged dataframe shape: (439, 21)


WORKING ON: CAS
There are 12 variants with p-value < 0.05 in glm
Number of variants in CAS for CADPS2: 2522
df_results shape: (2522, 14)
Merged dataframe shape: (440, 21)


WORKING ON: EAS
There are 8 variants with p-value < 0.05 in glm
Number of variants in EAS for CADPS2: 2680
df_results shape: (2680, 14)
Merged dataframe shape: (396, 21)


WORKING ON: EUR
There are 16 variants with p-value < 0.05 in glm
Number of variants in EUR for CADPS2: 11784
df_results shape: (11784, 14)
Merged dataframe shape: (493, 21)


WORKING ON: FIN
There are 8 variants with p-value < 0.05 in glm
Number of variants in FIN for CADPS2: 637
df_results shape: (637, 14)
Merged dataframe shape: (421, 21)


WORKING ON: MDE
There are 21 variants with p-value < 0.05 in glm
Number of variants in MDE for CADPS2: 2467
df_results shape: (2467, 14)
Merged dataframe shape: (418, 21)


WORKING ON: SAS
There are 29 variants with p-value < 0.05 in glm
Number of variants in SAS for CADPS2: 2039
df_results shape: (2039, 14)
Merged dataframe shape: (520, 21)


WORKING ON: CAH
There are 38 variants with p-value < 0.05 in glm
Number of variants in CAH for CADPS2: 5361
df_results shape: (5361, 14)
Merged dataframe shape: (990, 21)

## EXONIC VARIANTS

#### assoc

In [13]:
## extract region using plink

def exonicAssoc(ANCESTRY):
    
    ## Analysis start time
    ts_start = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   ASSOC START:   {ts_start}   =====================\n")

    ## Get ANCESTRY name
    print(f"Association test for {GENE_NAME} from {ANCESTRY} {analysis} Release 11 data.")
    
    ## Input files
    inputBfile = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_{GENE_NAME}"
    samplesToKeep = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}.samplestokeep"
    covariate = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_covariate_file.txt"
    variantsToKeep = f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.exonic.variantstoKeep.txt'
    outputAssocExonic = f"{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_{GENE_NAME}.assoc.allExonic"
    outputRawExonic = f"{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_{GENE_NAME}.raw.allExonic"
    
    # Print the command to be executed (for debugging purposes)
    print(f'Running Plink1.9 Association for ANCESTRY: {ANCESTRY}')
        
    ## Define plink2 command for extraction
    plinkAssocExonic = [
        f"{TOOL_DIR}/plink1.9",
        "--bfile", inputBfile,
        "--keep", samplesToKeep,
        "--extract", "range", variantsToKeep,
        "--assoc",
        "--maf", "0.01",
        "--mac", "2",
        "--hwe", "0.0001",
        "--adjust",
        "--allow-no-sex",
        "--ci", "0.95",
        "--out", outputAssocExonic
    ]

    ## Run plink2 command as bash subprocess
    subprocess.run(plinkAssocExonic, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)

    recodeA = [
        f"{TOOL_DIR}/plink1.9",
        "--bfile", inputBfile,
        "--keep", samplesToKeep,
        "--extract", "range", variantsToKeep,
        "--recode", "A",
        "--out", outputRawExonic
        ]

    subprocess.run(recodeA, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)
    
    ## Analysis end time
    ts_finish = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   ASSOC END:   {ts_finish}   =====================\n")
    
    ## Return ANCESTRY, position and gene
    return f"Association test performed on exonic variants: {ANCESTRY} in {GENE_NAME}"

In [14]:
for ances in ANCESTRIES:
    exonicAssoc(ances)

=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-14   =====================

Association test for CADPS2 from AAC NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: AAC


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-16   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-16   =====================

Association test for CADPS2 from AFR NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: AFR


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-18   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-18   =====================

Association test for CADPS2 from AJ NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: AJ


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-19   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-19   =====================

Association test for CADPS2 from AMR NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: AMR


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-21   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-21   =====================

Association test for CADPS2 from CAS NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: CAS


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-23   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-23   =====================

Association test for CADPS2 from EAS NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: EAS


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-24   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-24   =====================

Association test for CADPS2 from EUR NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: EUR


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-30   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-30   =====================

Association test for CADPS2 from FIN NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: FIN


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-31   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-31   =====================

Association test for CADPS2 from MDE NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: MDE


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-33   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-33   =====================

Association test for CADPS2 from SAS NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: SAS


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-35   =====================



=============   ASSOC START:   Date: 2026-02-25   Time: 17-55-35   =====================

Association test for CADPS2 from CAH NBA Release 11 data.
Running Plink1.9 Association for ANCESTRY: CAH


=============   ASSOC END:   Date: 2026-02-25   Time: 17-55-36   =====================

In [15]:
#Process results from plink assoc unadjusted analysis for CODING variants
#As there are very few or no significant variants with p-value < 0.05 - we will save results dataframe of all coding variants
ANCESTRIES = ['AFR', 'AAC', 'AJ', 'AMR', 'CAS', 'EUR', 'FIN', 'EAS', 'MDE', 'SAS', 'CAH']

for ANCESTRY in ANCESTRIES:
    try:
        ## Input files
        AssocExonic = f"{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_{GENE_NAME}.assoc.allExonic.assoc"
        RawExonic = f"{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_{GENE_NAME}.raw.allExonic.raw"
        
        #Look at assoc results
        freq = pd.read_csv(AssocExonic, sep='\s+')
        
        #Filter for significant variants p < 0.05 - if any
        sig_all_nonadj = freq[freq['P']<0.05]
        
        print(f'There are {len(sig_all_nonadj)} variants with p-value < 0.05')
    
        #Read in plink recoded data (.raw file)
        recode = pd.read_csv(RawExonic, sep='\s+')
    
        # Make a list from the column names
        column_names = recode.columns.tolist()
    
        # Drop the first 6 columns to keep the variants 
        variants = column_names[6:]
    
        print(f'Number of variants in {ANCESTRY} for CADPS2: {len(variants)}')
    
        # Pre-filter the dataset
        cases_data = recode[recode['PHENOTYPE'] == 2]
        controls_data = recode[recode['PHENOTYPE'] == 1]
    
        results = []
    
        # Pre-filter the dataset
        total_cases = cases_data.shape[0]
        total_controls = controls_data.shape[0]
        results = []
    
        for variant in variants:
            ## For PD cases
            hom_cases = (cases_data[variant] == 2).sum()
            het_cases = (cases_data[variant] == 1).sum()
            hom_ref_cases = (cases_data[variant] == 0).sum()  # Homozygous reference genotype
            missing_cases = total_cases - (hom_cases + het_cases + hom_ref_cases)  # Missing data count
            freq_cases = (2 * hom_cases + het_cases) / (2 * (total_cases - missing_cases))  # Adjust for missing data in denominator
    
            ## For controls
            hom_controls = (controls_data[variant] == 2).sum()
            het_controls = (controls_data[variant] == 1).sum()
            hom_ref_controls = (controls_data[variant] == 0).sum()  # Homozygous reference genotype
            missing_controls = total_controls - (hom_controls + het_controls + hom_ref_controls)  # Missing data count
            freq_controls = (2 * hom_controls + het_controls) / (2 * (total_controls - missing_controls))  # Adjust for missing data in denominator
        
            # Append results in dictionary format
            results.append({
                'Variant': variant,
                'Hom Cases': hom_cases,
                'Het Cases': het_cases,
                'Hom Ref Cases': hom_ref_cases,
                'Missing Cases': missing_cases,
                'Total Cases': total_cases,
                'Carrier Freq in Cases': freq_cases,
                'Hom Controls': hom_controls,
                'Het Controls': het_controls,
                'Hom Ref Controls': hom_ref_controls,
                'Missing Controls': missing_controls,
                'Total Controls': total_controls,
                'Carrier Freq in Controls': freq_controls
            })
    
        # Return
        df_results = pd.DataFrame(results)
        df_results['SNP'] = df_results['Variant'].apply(lambda x: x.rsplit('_', 1)[0])
    
        #Print dimensions of the df_results dataframe
        print(f'df_results shape: {df_results.shape}')
              
        #Merge with the assoc file
        sig_merge = freq[['SNP','A1','F_A','F_U','A2','L95','OR','U95','P']]
        merged = pd.merge(df_results, sig_merge, on='SNP', how='right')
        
        #Print dimensions of the merged dataframe (just adding more columns)
        print(f'Merged dataframe shape: {merged.shape}\n\n') 
        
        ## Save to CSV
        merged.to_csv(f'{ANA_DIR}/{ANCESTRY}/{ANCESTRY}_{GENE_NAME}.assoc.allExonic.txt', sep = '\t', index=False)    
    except: pass

There are 0 variants with p-value < 0.05
Number of variants in AFR for CADPS2: 25
df_results shape: (25, 14)
Merged dataframe shape: (2, 22)


There are 0 variants with p-value < 0.05
Number of variants in AAC for CADPS2: 19
df_results shape: (19, 14)
Merged dataframe shape: (2, 22)


There are 0 variants with p-value < 0.05
Number of variants in AJ for CADPS2: 10
df_results shape: (10, 14)
Merged dataframe shape: (1, 22)


There are 2 variants with p-value < 0.05
Number of variants in AMR for CADPS2: 22
df_results shape: (22, 14)
Merged dataframe shape: (2, 22)


There are 0 variants with p-value < 0.05
Number of variants in CAS for CADPS2: 13
df_results shape: (13, 14)
Merged dataframe shape: (2, 22)


There are 0 variants with p-value < 0.05
Number of variants in EUR for CADPS2: 66
df_results shape: (66, 14)
Merged dataframe shape: (1, 22)


There are 0 variants with p-value < 0.05
Number of variants in MDE for CADPS2: 11
df_results shape: (11, 14)
Merged dataframe shape: (1, 22)


There are 0 variants with p-value < 0.05
Number of variants in SAS for CADPS2: 7
df_results shape: (7, 14)
Merged dataframe shape: (1, 22)


There are 0 variants with p-value < 0.05
Number of variants in CAH for CADPS2: 21
df_results shape: (21, 14)
Merged dataframe shape: (2, 22)

#### GLM

In [16]:
## extract region using plink

def exonicGLM(ANCESTRY):
    
    ## Analysis start time
    ts_start = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   GLM START:   {ts_start}   =====================\n")

    ## Get ANCESTRY name
    print(f"GLM test for {GENE_NAME} from {ANCESTRY} NBA Release 11 data.")


    inputpfile = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_{GENE_NAME}"
    outputGLMExonic = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_{GENE_NAME}.glm.allExonic"
    outputRawExonic = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_{GENE_NAME}.raw.allExonic"
    variantsToKeep = f'{ANA_DIR}/{ANCESTRY}/VariantDescriptives/{ANCESTRY}_{GENE_NAME}.exonic.variantstoKeep.txt'
    samplesToKeep = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}.samplestokeep"
    covariate = f"{ANA_DIR}/{ANCESTRY}/InputFiles/{ANCESTRY}_covariate_file.txt"
    
    # Print the command to be executed (for debugging purposes)
    print(f'Running Plink2 GLM for ANCESTRY: {ANCESTRY}')
    
    
    ## Define plink2 command for extraction
    plinkGLMExonic = [
        f"{TOOL_DIR}/plink2",
        "--pfile", inputpfile,
        "--keep", samplesToKeep,
        "--extract", "range", variantsToKeep,
        "--glm",
        "--maf", "0.01",
        "--mac", "2",
        "--hwe", "0.0001", "keep-fewhet",
        "--adjust",
        "--allow-no-sex",
        "--ci", "0.95",
        "--covar", covariate,
        "--covar-variance-standardize",
        "--covar-name", "SEX,AGE,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10",
        "--out", outputGLMExonic
    ]

    ## Run plink2 command as bash subprocess
    subprocess.run(plinkGLMExonic, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)

    recodeA = [
        f"{TOOL_DIR}/plink2",
        "--pfile", inputpfile,
        "--keep", samplesToKeep,
        "--extract", "range", variantsToKeep,
        "--recode", "A",
        "--out", outputRawExonic
        ]

    subprocess.run(recodeA, stderr=subprocess.PIPE, stdout=subprocess.PIPE, check=False)
    
    ## Analysis end time
    ts_finish = datetime.now().strftime('Date: %Y-%m-%d   Time: %H-%M-%S')
    print(f"\n\n=============   GLM END:   {ts_finish}   =====================\n")
    
    ## Return ANCESTRY, position and gene
    return f"GLM test performed on exonic variants: {ANCESTRY} in {GENE_NAME}"

In [17]:
for ances in ANCESTRIES:
    exonicGLM(ances)

=============   GLM START:   Date: 2026-02-25   Time: 17-55-39   =====================

GLM test for CADPS2 from AFR NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: AFR


=============   GLM END:   Date: 2026-02-25   Time: 17-55-41   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-41   =====================

GLM test for CADPS2 from AAC NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: AAC


=============   GLM END:   Date: 2026-02-25   Time: 17-55-42   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-42   =====================

GLM test for CADPS2 from AJ NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: AJ


=============   GLM END:   Date: 2026-02-25   Time: 17-55-44   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-44   =====================

GLM test for CADPS2 from AMR NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: AMR


=============   GLM END:   Date: 2026-02-25   Time: 17-55-46   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-46   =====================

GLM test for CADPS2 from CAS NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: CAS


=============   GLM END:   Date: 2026-02-25   Time: 17-55-47   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-47   =====================

GLM test for CADPS2 from EUR NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: EUR


=============   GLM END:   Date: 2026-02-25   Time: 17-55-49   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-49   =====================

GLM test for CADPS2 from FIN NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: FIN


=============   GLM END:   Date: 2026-02-25   Time: 17-55-51   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-51   =====================

GLM test for CADPS2 from EAS NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: EAS


=============   GLM END:   Date: 2026-02-25   Time: 17-55-52   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-52   =====================

GLM test for CADPS2 from MDE NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: MDE


=============   GLM END:   Date: 2026-02-25   Time: 17-55-53   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-53   =====================

GLM test for CADPS2 from SAS NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: SAS


=============   GLM END:   Date: 2026-02-25   Time: 17-55-54   =====================



=============   GLM START:   Date: 2026-02-25   Time: 17-55-54   =====================

GLM test for CADPS2 from CAH NBA Release 11 data.
Running Plink2 GLM for ANCESTRY: CAH


=============   GLM END:   Date: 2026-02-25   Time: 17-55-56   =====================

In [20]:
for ANCESTRY in ANCESTRIES:
    try:
        glm_file = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_CADPS2.glm.allExonic.PHENO1.glm.logistic.hybrid"
        df = pd.read_csv(glm_file, sep='\t') 
        df = df.rename(columns={'LOG(OR)_SE': 'SE'})
        df.to_csv(glm_file, sep='\t', index=False)
    except:
        pass

In [47]:
#Process results from plink glm analysis for EXONIC variants
#As there are very few or no significant variants with p-value < 0.05 - we will save results dataframe of all coding variants

ANCESTRIES = ['AAC', 'AFR', 'AJ', 'AMR', 'CAS', 'EAS', 'EUR', 'FIN', 'MDE', 'SAS', 'CAH']

for ANCESTRY in ANCESTRIES:
    try:
        print(f'WORKING ON: {ANCESTRY}')

        glm_file = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_{GENE_NAME}.glm.allExonic.PHENO1.glm.logistic.hybrid"
        raw_file = f"{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_{GENE_NAME}.raw.allExonic.raw"

        
        #Read in glm results
        glm = pd.read_csv(glm_file, sep='\s+')
        glm_add = glm[glm['TEST']=="ADD"]
        
        #Filter for significant variants p < 0.05 - if any
        significant = glm_add[glm_add['P']<0.05]
        print(f'There are {len(significant)} variants with p-value < 0.05 in glm')
        
        #Read in plink recoded data (.raw file)
        recode = pd.read_csv(raw_file, sep='\s+')
    
        # Make a list from the column names
        column_names = recode.columns.tolist()
    
        # Drop the first 6 columns to keep the variants 
        variants = column_names[6:]
    
        print(f'Number of variants in {ANCESTRY} for CADPS2: {len(variants)}')
    
        # Pre-filter the dataset
        cases_data = recode[recode['PHENOTYPE'] == 2]
        controls_data = recode[recode['PHENOTYPE'] == 1]
    
        results = []
    
        # Pre-filter the dataset
        total_cases = cases_data.shape[0]
        total_controls = controls_data.shape[0]
        results = []
    
        for variant in variants:
            ## For PD cases
            hom_cases = (cases_data[variant] == 2).sum()
            het_cases = (cases_data[variant] == 1).sum()
            hom_ref_cases = (cases_data[variant] == 0).sum()  # Homozygous reference genotype
            missing_cases = total_cases - (hom_cases + het_cases + hom_ref_cases)  # Missing data count
            freq_cases = (2 * hom_cases + het_cases) / (2 * (total_cases - missing_cases))  # Adjust for missing data in denominator
    
            ## For controls
            hom_controls = (controls_data[variant] == 2).sum()
            het_controls = (controls_data[variant] == 1).sum()
            hom_ref_controls = (controls_data[variant] == 0).sum()  # Homozygous reference genotype
            missing_controls = total_controls - (hom_controls + het_controls + hom_ref_controls)  # Missing data count
            freq_controls = (2 * hom_controls + het_controls) / (2 * (total_controls - missing_controls))  # Adjust for missing data in denominator
        
            # Append results in dictionary format
            results.append({
                'Variant': variant,
                'Hom Cases': hom_cases,
                'Het Cases': het_cases,
                'Hom Ref Cases': hom_ref_cases,
                'Missing Cases': missing_cases,
                'Total Cases': total_cases,
                'Carrier Freq in Cases': freq_cases,
                'Hom Controls': hom_controls,
                'Het Controls': het_controls,
                'Hom Ref Controls': hom_ref_controls,
                'Missing Controls': missing_controls,
                'Total Controls': total_controls,
                'Carrier Freq in Controls': freq_controls
            })
    
        # Return
        df_results = pd.DataFrame(results)
        df_results['ID'] = df_results['Variant'].apply(lambda x: x.rsplit('_', 1)[0])
    
        #Print dimensions of the df_results dataframe
        print(f'df_results shape: {df_results.shape}')
        
        #Merge with the glm file
        sig_merge = glm_add[['ID','A1','A1_FREQ','OBS_CT','OR','SE','Z_STAT','P']]
        merged = pd.merge(df_results, sig_merge, on='ID', how='right')
        
        #Print dimensions of the merged dataframe (just adding more columns)
        print(f'Merged dataframe shape: {merged.shape}')
        
        ## Save to CSV
        merged.to_csv(f'{ANA_DIR}/{ANCESTRY}/{ANCESTRY}_{GENE_NAME}.glm.allExonic.txt', sep = '\t', index=False)   
    except Exception as e:
        print(e)
        pass

WORKING ON: AAC
There are 0 variants with p-value < 0.05 in glm
Number of variants in AAC for CADPS2: 19
df_results shape: (19, 14)
Merged dataframe shape: (2, 21)
WORKING ON: AFR
There are 0 variants with p-value < 0.05 in glm
Number of variants in AFR for CADPS2: 25
df_results shape: (25, 14)
Merged dataframe shape: (2, 21)
WORKING ON: AJ
There are 0 variants with p-value < 0.05 in glm
Number of variants in AJ for CADPS2: 10
df_results shape: (10, 14)
Merged dataframe shape: (1, 21)
WORKING ON: AMR
There are 0 variants with p-value < 0.05 in glm
Number of variants in AMR for CADPS2: 22
df_results shape: (22, 14)
Merged dataframe shape: (2, 21)
WORKING ON: CAS
There are 0 variants with p-value < 0.05 in glm
Number of variants in CAS for CADPS2: 13
df_results shape: (13, 14)
Merged dataframe shape: (2, 21)
WORKING ON: EAS
[Errno 2] No such file or directory: '/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/GLM/EAS_CADPS2.glm.allExonic.PHENO1.glm.logistic.hybrid'
WORKING ON: EUR
There are 0 variants with p-value < 0.05 in glm
Number of variants in EUR for CADPS2: 66
df_results shape: (66, 14)
Merged dataframe shape: (1, 21)
WORKING ON: FIN
[Errno 2] No such file or directory: '/home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/GLM/FIN_CADPS2.glm.allExonic.PHENO1.glm.logistic.hybrid'
WORKING ON: MDE
There are 0 variants with p-value < 0.05 in glm
Number of variants in MDE for CADPS2: 11
df_results shape: (11, 14)
Merged dataframe shape: (1, 21)
WORKING ON: SAS
There are 0 variants with p-value < 0.05 in glm
Number of variants in SAS for CADPS2: 7
df_results shape: (7, 14)
Merged dataframe shape: (1, 21)
WORKING ON: CAH
There are 0 variants with p-value < 0.05 in glm
Number of variants in CAH for CADPS2: 21
df_results shape: (21, 14)
Merged dataframe shape: (2, 21)

## Summary

In [48]:
import shutil
import glob

classes1 = ('allVariants','allExonic')
ANCESTRIES = ['AAC', 'AFR', 'AJ', 'AMR', 'CAS', 'EAS', 'EUR', 'FIN', 'MDE', 'SAS', 'CAH']

for i in ANCESTRIES:
    current_dir = os.path.join(ANA_DIR, str(i))
    summary_dir = os.path.join(current_dir, "Summary")
    if not os.path.exists(summary_dir):
        os.makedirs(summary_dir)

    pattern = os.path.join(current_dir, f"{i}_*")
    for file_path in glob.glob(pattern):
        if os.path.isfile(file_path):
            file_name = os.path.basename(file_path)
            destination = os.path.join(summary_dir, file_name)
            shutil.move(file_path, destination)

In [49]:
for GENE_NAME in GENE_DICT:
    for ANCESTRY in ANCESTRIES:
        for class1 in classes1:
            try:
                print(f"Working on {ANCESTRY}, class: {class1}\n")
                ## Input files
                summary_dir = f"{ANA_DIR}/{ANCESTRY}/Summary"
                base_path = f'{summary_dir}/{ANCESTRY}_{GENE_NAME}'
                glm = f"{base_path}.glm.{class1}"
                assoc = f"{base_path}.assoc.{class1}"
                
                glm_df = pd.read_csv(f"{glm}.txt", sep='\t', header=0)
                glm_adj_df = pd.read_csv(f'{ANA_DIR}/{ANCESTRY}/GLM/{ANCESTRY}_CADPS2.glm.{class1}.PHENO1.glm.logistic.hybrid.adjusted', sep='\t', header=0)            
                glm_merge = pd.merge(glm_df, glm_adj_df[['ID', 'BONF']], how='inner', on='ID')
                
                assoc_df = pd.read_csv(f"{assoc}.txt", sep='\t', header=0)   
                assoc_adj_df = pd.read_csv(f'{ANA_DIR}/{ANCESTRY}/Association/{ANCESTRY}_CADPS2.assoc.{class1}.assoc.adjusted', sep='\s+', header=0)           
                assoc_merge = pd.merge(assoc_df, assoc_adj_df[['SNP', 'BONF']], how='inner', on='SNP')
                assoc_merge['ID'] = assoc_merge['SNP']
                assoc_merge['A1_FREQ'] = assoc_merge['F_A']

                os.makedirs(summary_dir, exist_ok = True)

                glm_out = f"{summary_dir}/{ANCESTRY}_{GENE_NAME}_{class1}.glm"
                assoc_out = f"{summary_dir}/{ANCESTRY}_{GENE_NAME}_{class1}.assoc"
                glm_merge.to_csv(glm_out, index=False)
                assoc_merge.to_csv(assoc_out, index=False)
                
            except Exception as e:
                print(e)
            pass

Working on AAC, class: allVariants

Working on AAC, class: allExonic

Working on AFR, class: allVariants

Working on AFR, class: allExonic

Working on AJ, class: allVariants

Working on AJ, class: allExonic

Working on AMR, class: allVariants

Working on AMR, class: allExonic

Working on CAS, class: allVariants

Working on CAS, class: allExonic

Working on EAS, class: allVariants

Working on EAS, class: allExonic

[Errno 2] No such file or directory: '/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/Summary//EAS_CADPS2.glm.allExonic.txt'
Working on EUR, class: allVariants

Working on EUR, class: allExonic

Working on FIN, class: allVariants

Working on FIN, class: allExonic

[Errno 2] No such file or directory: '/home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/Summary//FIN_CADPS2.glm.allExonic.txt'
Working on MDE, class: allVariants

Working on MDE, class: allExonic

Working on SAS, class: allVariants

Working on SAS, class: allExonic

Working on CAH, class: allVariants

Working on CAH, class: allExonic

In [69]:
ANCESTRIES = ['AAC', 'AFR', 'AJ', 'AMR', 'CAS', 'EAS', 'EUR', 'FIN', 'MDE', 'SAS', 'CAH']

for ANCESTRY in  ANCESTRIES:
    for classes in classes1:
        try:
            summary_dir = f"{ANA_DIR}/{ANCESTRY}/Summary"
            base = f"{summary_dir}/{ANCESTRY}_CADPS2_{classes}"
            df_glm = pd.read_csv(f"{base}.glm", sep=',', header=0)
            df_assoc = pd.read_csv(f"{base}.assoc", sep=',', header=0) 

            df_glm.to_csv(f"{summary_dir}/{ANCESTRY}_CADPS2_{classes}_processed_glm.csv", index=False)
            df_assoc.to_csv(f"{summary_dir}/{ANCESTRY}_CADPS2_{classes}_processed_assoc.csv", index=False)              
        except:
            pass

summary_stats = []
analysis1 = {'glm', 'assoc'}
for ANCESTRY in ANCESTRIES:
    for classes in classes1:
        for a in analysis1:
            try:
                summary_dir = f"{ANA_DIR}/{ANCESTRY}/Summary"
                base = f"{summary_dir}/{ANCESTRY}_CADPS2_{classes}_processed_{a}.csv"
                print(f"Read {base}")
                df = pd.read_csv(base, header=0)
                df.insert(0, "Gene", GENE_NAME)
                df.insert(1, "Ancestry", ANCESTRY)
                df.insert(2, "Analysis", a)
                df.insert(3, "Variant type", classes)
                summary_stats.append(df)
            except Exception as e:
                print(e)
                pass
                    
summary_stats = pd.concat(summary_stats, ignore_index=True) if summary_stats else pd.DataFrame()
summary_stats

Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/Summary/AAC_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/Summary/AAC_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/Summary/AAC_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AAC/Summary/AAC_CADPS2_allExonic_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/Summary/AFR_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/Summary/AFR_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/Summary/AFR_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AFR/Summary/AFR_CADPS2_allExonic_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/Summary/AJ_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/Summary/AJ_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/Summary/AJ_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AJ/Summary/AJ_CADPS2_allExonic_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/Summary/AMR_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/Summary/AMR_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/Summary/AMR_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/AMR/Summary/AMR_CADPS2_allExonic_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/Summary/CAS_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/Summary/CAS_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/Summary/CAS_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAS/Summary/CAS_CADPS2_allExonic_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/Summary/EAS_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/Summary/EAS_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/Summary/EAS_CADPS2_allExonic_processed_assoc.csv
[Errno 2] No such file or directory: '/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/Summary/EAS_CADPS2_allExonic_processed_assoc.csv'
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/Summary/EAS_CADPS2_allExonic_processed_glm.csv
[Errno 2] No such file or directory: '/home/jupyter/workspace/ws_files/NahuTestR11/NBA/EAS/Summary/EAS_CADPS2_allExonic_processed_glm.csv'
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EUR/Summary/EUR_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EUR/Summary/EUR_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EUR/Summary/EUR_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/EUR/Summary/EUR_CADPS2_allExonic_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/Summary/FIN_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/Summary/FIN_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/Summary/FIN_CADPS2_allExonic_processed_assoc.csv
[Errno 2] No such file or directory: '/home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/Summary/FIN_CADPS2_allExonic_processed_assoc.csv'
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/Summary/FIN_CADPS2_allExonic_processed_glm.csv
[Errno 2] No such file or directory: '/home/jupyter/workspace/ws_files/NahuTestR11/NBA/FIN/Summary/FIN_CADPS2_allExonic_processed_glm.csv'
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/Summary/MDE_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/Summary/MDE_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/Summary/MDE_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/MDE/Summary/MDE_CADPS2_allExonic_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/Summary/SAS_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/Summary/SAS_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/Summary/SAS_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/SAS/Summary/SAS_CADPS2_allExonic_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/Summary/CAH_CADPS2_allVariants_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/Summary/CAH_CADPS2_allVariants_processed_glm.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/Summary/CAH_CADPS2_allExonic_processed_assoc.csv
Read /home/jupyter/workspace/ws_files/NahuTestR11/NBA/CAH/Summary/CAH_CADPS2_allExonic_processed_glm.csv

,Gene,Ancestry,Analysis,Variant type,Variant,Hom Cases,Het Cases,Hom Ref Cases,Missing Cases,Total Cases,...,L95,OR,SE,U95,P,BONF,ID,A1_FREQ,OBS_CT,Z_STAT
0,CADPS2,AAC,assoc,allVariants,chr7:122318683:A:C_C,3,30,445,0,478,...,0.6128,0.9273,0.211300,1.403,0.720800,1.0000,chr7:122318683:A:C,0.037660,NaN,NaN
1,CADPS2,AAC,assoc,allVariants,chr7:122319215:G:T_T,0,13,462,3,478,...,0.4687,0.9249,0.346800,1.825,0.821900,1.0000,chr7:122319215:G:T,0.013680,NaN,NaN
2,CADPS2,AAC,assoc,allVariants,chr7:122319877:A:G_G,3,30,445,0,478,...,0.6128,0.9273,0.211300,1.403,0.720800,1.0000,chr7:122319877:A:G,0.037660,NaN,NaN
3,CADPS2,AAC,assoc,allVariants,chr7:122320660:G:A_A,0,14,461,3,478,...,0.5560,1.092,0.344300,2.144,0.798500,1.0000,chr7:122320660:G:A,0.014740,NaN,NaN
4,CADPS2,AAC,assoc,allVariants,chr7:122321156:T:C_C,0,11,465,2,478,...,0.5173,1.109,0.389100,2.378,0.790000,1.0000,chr7:122321156:T:C,0.011550,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13554,CADPS2,CAH,glm,allVariants,chr7:122886666:C:T_C,691,20,0,74,785,...,NaN,1.12946,0.373680,NaN,0.744588,1.0000,chr7:122886666:C:T,0.025055,971.0,0.325783
13555,CADPS2,CAH,assoc,allExonic,chr7:122621693:C:T_T,0,27,758,0,785,...,0.7125,1.522,NaN,3.253,0.274600,0.5492,chr7:122621693:C:T,0.017200,NaN,NaN
13556,CADPS2,CAH,assoc,allExonic,chr7:122698916:C:T_T,0,40,745,0,785,...,0.7056,1.268,NaN,2.279,0.426300,0.8525,chr7:122698916:C:T,0.025480,NaN,NaN
13557,CADPS2,CAH,glm,allExonic,chr7:122621693:C:T_C,757,26,0,2,785,...,NaN,1.28672,0.457647,NaN,0.581736,1.0000,chr7:122621693:C:T,0.016971,971.0,0.550851
13558,CADPS2,CAH,glm,allExonic,chr7:122698916:C:T_C,744,40,0,1,785,...,NaN,1.295,0.411734,NaN,0.530097,1.0000,chr7:122698916:C:T,0.020084,971.0,0.627858

In [70]:
summary_stats.columns

Index(['Gene', 'Ancestry', 'Analysis', 'Variant type', 'Variant', 'Hom Cases',
       'Het Cases', 'Hom Ref Cases', 'Missing Cases', 'Total Cases',
       'Carrier Freq in Cases', 'Hom Controls', 'Het Controls',
       'Hom Ref Controls', 'Missing Controls', 'Total Controls',
       'Carrier Freq in Controls', 'SNP', 'A1', 'F_A', 'F_U', 'A2', 'L95',
       'OR', 'SE', 'U95', 'P', 'BONF', 'ID', 'A1_FREQ', 'OBS_CT', 'Z_STAT'],
      dtype='object')

In [71]:
common_cols = ['Gene','Ancestry','Analysis','Variant type',	
               'ID', 'A1', 'A1_FREQ', 'P', 'BONF', 
               'OR', 'SE', 'L95', 'U95', 
               'Hom Cases', 'Het Cases', 'Hom Ref Cases', 
               'Missing Cases', 'Total Cases', 'Carrier Freq in Cases', 
               'Hom Controls', 'Het Controls', 'Hom Ref Controls', 
               'Missing Controls', 'Total Controls', 'Carrier Freq in Controls']

In [72]:
summary_stats = summary_stats[common_cols]
summary_stats

,Gene,Ancestry,Analysis,Variant type,ID,A1,A1_FREQ,P,BONF,OR,...,Hom Ref Cases,Missing Cases,Total Cases,Carrier Freq in Cases,Hom Controls,Het Controls,Hom Ref Controls,Missing Controls,Total Controls,Carrier Freq in Controls
0,CADPS2,AAC,assoc,allVariants,chr7:122318683:A:C,C,0.037660,0.720800,1.0000,0.9273,...,445,0,478,0.037657,2,62,751,0,815,0.040491
1,CADPS2,AAC,assoc,allVariants,chr7:122319215:G:T,T,0.013680,0.821900,1.0000,0.9249,...,462,3,478,0.013684,1,22,789,3,815,0.014778
2,CADPS2,AAC,assoc,allVariants,chr7:122319877:A:G,G,0.037660,0.720800,1.0000,0.9273,...,445,0,478,0.037657,2,62,751,0,815,0.040491
3,CADPS2,AAC,assoc,allVariants,chr7:122320660:G:A,A,0.014740,0.798500,1.0000,1.092,...,461,3,478,0.014737,1,20,793,1,815,0.013514
4,CADPS2,AAC,assoc,allVariants,chr7:122321156:T:C,C,0.011550,0.790000,1.0000,1.109,...,465,2,478,0.011555,0,17,798,0,815,0.010429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13554,CADPS2,CAH,glm,allVariants,chr7:122886666:C:T,T,0.025055,0.744588,1.0000,1.12946,...,0,74,785,0.985935,334,6,0,56,396,0.991176
13555,CADPS2,CAH,assoc,allExonic,chr7:122621693:C:T,T,0.017200,0.274600,0.5492,1.522,...,758,0,785,0.017197,0,9,387,0,396,0.011364
13556,CADPS2,CAH,assoc,allExonic,chr7:122698916:C:T,T,0.025480,0.426300,0.8525,1.268,...,745,0,785,0.025478,0,16,380,0,396,0.020202
13557,CADPS2,CAH,glm,allExonic,chr7:122621693:C:T,T,0.016971,0.581736,1.0000,1.28672,...,0,2,785,0.983397,385,9,0,2,396,0.988579
13558,CADPS2,CAH,glm,allExonic,chr7:122698916:C:T,T,0.020084,0.530097,1.0000,1.295,...,0,1,785,0.974490,377,16,0,3,396,0.979644

In [73]:
summary_stats['Variant type'].value_counts().to_frame()

              count
Variant type
allVariants   13531
allExonic        28

In [74]:
summary_stats.to_csv(f"{RESU_DIR}/{analysis}/{GENE_NAME}_{analysis}_assocglm_SummaryStats.csv",  index=False)

### Significant stats

In [75]:
significant_stats = summary_stats[
    (summary_stats['P'] <= 0.05) &
    (summary_stats['Hom Cases'] != 0) &
    (summary_stats['Het Cases'] != 0) &
    (summary_stats['Hom Controls'] != 0) &
    (summary_stats['Het Controls'] != 0)
]
significant_stats

,Gene,Ancestry,Analysis,Variant type,ID,A1,A1_FREQ,P,BONF,OR,...,Hom Ref Cases,Missing Cases,Total Cases,Carrier Freq in Cases,Hom Controls,Het Controls,Hom Ref Controls,Missing Controls,Total Controls,Carrier Freq in Controls
712,CADPS2,AAC,assoc,allVariants,chr7:122636614:C:T,T,0.042020,0.017990,1.0,1.698,...,437,2,478,0.042017,1,39,774,1,815,0.025184
725,CADPS2,AAC,assoc,allVariants,chr7:122642574:T:C,C,0.042020,0.013630,1.0,1.741,...,437,2,478,0.042017,1,38,775,1,815,0.024570
1081,CADPS2,AAC,assoc,allVariants,chr7:122830346:T:A,A,0.062760,0.003228,1.0,1.722,...,423,0,478,0.062762,1,59,755,0,815,0.037423
1082,CADPS2,AAC,assoc,allVariants,chr7:122830348:C:A,A,0.062760,0.003228,1.0,1.722,...,423,0,478,0.062762,1,59,755,0,815,0.037423
1083,CADPS2,AAC,assoc,allVariants,chr7:122830463:C:T,T,0.062760,0.003228,1.0,1.722,...,423,0,478,0.062762,1,59,755,0,815,0.037423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13306,CADPS2,CAH,glm,allVariants,chr7:122736871:T:C,C,0.016378,0.012005,1.0,0.350223,...,0,66,785,0.991655,338,8,0,50,396,0.988439
13330,CADPS2,CAH,glm,allVariants,chr7:122751933:C:G,G,0.010671,0.024358,1.0,5.50309,...,0,70,785,0.993007,349,2,0,45,396,0.997151
13518,CADPS2,CAH,glm,allVariants,chr7:122863970:C:T,T,0.010892,0.046510,1.0,3.60987,...,0,60,785,0.993103,349,2,0,45,396,0.997151
13533,CADPS2,CAH,glm,allVariants,chr7:122874108:T:C,C,0.010958,0.047693,1.0,3.53735,...,0,62,785,0.993084,348,2,0,46,396,0.997143
13546,CADPS2,CAH,glm,allVariants,chr7:122880617:T:C,C,0.023779,0.035897,1.0,0.481116,...,0,102,785,0.985359,310,11,0,75,396,0.982866

In [76]:
gene = 'CADPS2'
significant_stats.to_csv(f"{RESU_DIR}/{analysis}/{gene}_{analysis}_assocglm_SignificantVariantsNonAdjusted.csv", index=False)

In [77]:
significant_stats_bonf = significant_stats[(significant_stats['BONF'] <= 0.05)]
significant_stats_bonf

,Gene,Ancestry,Analysis,Variant type,ID,A1,A1_FREQ,P,BONF,OR,...,Hom Ref Cases,Missing Cases,Total Cases,Carrier Freq in Cases,Hom Controls,Het Controls,Hom Ref Controls,Missing Controls,Total Controls,Carrier Freq in Controls
5600,CADPS2,AMR,assoc,allVariants,chr7:122327354:C:T,T,0.02264,5.745000e-08,2.430000e-05,0.4803,...,1985,46,2122,0.022640,4,121,1277,84,1486,0.046006
5604,CADPS2,AMR,assoc,allVariants,chr7:122332314:G:A,A,0.01806,1.034000e-07,4.373000e-05,0.4538,...,2002,46,2122,0.018064,4,101,1294,87,1486,0.038956
5619,CADPS2,AMR,assoc,allVariants,chr7:122379319:T:C,C,0.02876,5.881000e-05,2.488000e-02,0.5989,...,1953,53,2122,0.028758,3,126,1272,85,1486,0.047109
5636,CADPS2,AMR,assoc,allVariants,chr7:122412185:C:G,G,0.04055,2.638000e-07,1.116000e-04,2.202,...,1929,26,2122,0.040553,1,53,1406,26,1486,0.018836
5710,CADPS2,AMR,assoc,allVariants,chr7:122457940:A:G,G,0.02703,2.747000e-08,1.162000e-05,0.5009,...,1981,32,2122,0.027033,1,150,1295,40,1486,0.052559
5730,CADPS2,AMR,assoc,allVariants,chr7:122468037:T:C,C,0.03887,1.234000e-06,5.220000e-04,2.115,...,1937,25,2122,0.038865,1,53,1412,20,1486,0.018759
5733,CADPS2,AMR,assoc,allVariants,chr7:122469116:A:G,G,0.05257,7.105000e-05,3.006000e-02,1.627,...,1904,1,2122,0.052570,2,94,1390,0,1486,0.032974
5785,CADPS2,AMR,assoc,allVariants,chr7:122539483:G:A,A,0.05631,5.209000e-05,2.203000e-02,1.613,...,1887,0,2122,0.056315,3,100,1383,0,1486,0.035666
5794,CADPS2,AMR,assoc,allVariants,chr7:122554232:G:T,T,0.04080,1.045000e-04,4.419000e-02,1.731,...,1949,2,2122,0.040802,2,67,1411,6,1486,0.023986
5795,CADPS2,AMR,assoc,allVariants,chr7:122554867:AT:A,A,0.04080,1.045000e-04,4.419000e-02,1.731,...,1949,2,2122,0.040802,2,67,1411,6,1486,0.023986
5796,CADPS2,AMR,assoc,allVariants,chr7:122556818:C:A,A,0.04080,1.045000e-04,4.419000e-02,1.731,...,1949,2,2122,0.040802,2,67,1411,6,1486,0.023986
5797,CADPS2,AMR,assoc,allVariants,chr7:122557554:G:A,A,0.04082,1.030000e-04,4.355000e-02,1.732,...,1948,3,2122,0.040821,2,67,1411,6,1486,0.023986
5798,CADPS2,AMR,assoc,allVariants,chr7:122558832:ACT:A,A,0.04080,1.045000e-04,4.419000e-02,1.731,...,1949,2,2122,0.040802,2,67,1411,6,1486,0.023986
5799,CADPS2,AMR,assoc,allVariants,chr7:122561914:T:C,C,0.04059,8.945000e-05,3.784000e-02,1.745,...,1949,3,2122,0.040585,2,66,1411,7,1486,0.023665
5800,CADPS2,AMR,assoc,allVariants,chr7:122562692:CTCA:C,C,0.04059,8.945000e-05,3.784000e-02,1.745,...,1949,3,2122,0.040585,2,66,1411,7,1486,0.023665
5801,CADPS2,AMR,assoc,allVariants,chr7:122562761:G:T,T,0.04059,8.945000e-05,3.784000e-02,1.745,...,1949,3,2122,0.040585,2,66,1411,7,1486,0.023665
5803,CADPS2,AMR,assoc,allVariants,chr7:122563364:C:T,T,0.04059,8.945000e-05,3.784000e-02,1.745,...,1949,3,2122,0.040585,2,66,1411,7,1486,0.023665
5804,CADPS2,AMR,assoc,allVariants,chr7:122564124:T:G,G,0.02754,6.142000e-10,2.598000e-07,0.4718,...,1977,34,2122,0.027538,1,163,1293,29,1486,0.056623
5805,CADPS2,AMR,assoc,allVariants,chr7:122565119:T:G,G,0.04059,8.945000e-05,3.784000e-02,1.745,...,1949,3,2122,0.040585,2,66,1411,7,1486,0.023665
5807,CADPS2,AMR,assoc,allVariants,chr7:122570777:G:A,A,0.04060,9.001000e-05,3.807000e-02,1.745,...,1948,4,2122,0.040604,2,66,1410,8,1486,0.023681
5808,CADPS2,AMR,assoc,allVariants,chr7:122571995:C:T,T,0.04059,8.945000e-05,3.784000e-02,1.745,...,1949,3,2122,0.040585,2,66,1411,7,1486,0.023665
5810,CADPS2,AMR,assoc,allVariants,chr7:122572513:G:C,C,0.04059,8.945000e-05,3.784000e-02,1.745,...,1949,3,2122,0.040585,2,66,1411,7,1486,0.023665
5811,CADPS2,AMR,assoc,allVariants,chr7:122572844:C:A,A,0.04059,8.945000e-05,3.784000e-02,1.745,...,1949,3,2122,0.040585,2,66,1411,7,1486,0.023665
5812,CADPS2,AMR,assoc,allVariants,chr7:122573413:A:G,G,0.04037,1.070000e-04,4.526000e-02,1.736,...,1949,4,2122,0.040368,2,66,1411,7,1486,0.023665
5817,CADPS2,AMR,assoc,allVariants,chr7:122578405:G:A,A,0.04037,1.070000e-04,4.526000e-02,1.736,...,1949,4,2122,0.040368,2,66,1411,7,1486,0.023665
5819,CADPS2,AMR,assoc,allVariants,chr7:122584176:C:CA,CA,0.04745,8.902000e-05,3.765000e-02,1.664,...,1919,4,2122,0.047450,3,80,1396,7,1486,0.029074
5820,CADPS2,AMR,assoc,allVariants,chr7:122587458:T:C,C,0.04745,8.902000e-05,3.765000e-02,1.664,...,1919,4,2122,0.047450,3,80,1396,7,1486,0.029074
5822,CADPS2,AMR,assoc,allVariants,chr7:122590399:C:T,T,0.04745,8.902000e-05,3.765000e-02,1.664,...,1919,4,2122,0.047450,3,80,1396,7,1486,0.029074
5823,CADPS2,AMR,assoc,allVariants,chr7:122592125:T:C,C,0.04887,5.877000e-05,2.486000e-02,1.674,...,1913,4,2122,0.048867,3,82,1393,8,1486,0.029770
5826,CADPS2,AMR,assoc,allVariants,chr7:122593569:A:G,G,0.04745,8.902000e-05,3.765000e-02,1.664,...,1919,4,2122,0.047450,3,80,1396,7,1486,0.029074
5827,CADPS2,AMR,assoc,allVariants,chr7:122594375:CATA:C,C,0.04887,5.740000e-05,2.428000e-02,1.676,...,1913,4,2122,0.048867,3,82,1394,7,1486,0.029750
5829,CADPS2,AMR,assoc,allVariants,chr7:122595052:T:C,C,0.04887,5.740000e-05,2.428000e-02,1.676,...,1913,4,2122,0.048867,3,82,1394,7,1486,0.029750
5830,CADPS2,AMR,assoc,allVariants,chr7:122596210:C:A,A,0.04747,8.760000e-05,3.705000e-02,1.664,...,1918,5,2122,0.047473,3,80,1396,7,1486,0.029074
5831,CADPS2,AMR,assoc,allVariants,chr7:122599121:C:T,T,0.04887,5.740000e-05,2.428000e-02,1.676,...,1913,4,2122,0.048867,3,82,1394,7,1486,0.029750
5832,CADPS2,AMR,assoc,allVariants,chr7:122599635:T:C,C,0.04743,9.046000e-05,3.826000e-02,1.663,...,1920,3,2122,0.047428,3,80,1396,7,1486,0.029074
5833,CADPS2,AMR,assoc,allVariants,chr7:122600574:C:G,G,0.02800,4.483000e-10,1.896000e-07,0.4719,...,1976,33,2122,0.028004,1,166,1293,26,1486,0.057534
5834,CADPS2,AMR,assoc,allVariants,chr7:122600844:G:A,A,0.04769,1.027000e-04,4.346000e-02,1.652,...,1918,4,2122,0.047686,3,81,1395,7,1486,0.029412
5838,CADPS2,AMR,assoc,allVariants,chr7:122607010:C:T,T,0.04743,9.046000e-05,3.826000e-02,1.663,...,1920,3,2122,0.047428,3,80,1396,7,1486,0.029074
5842,CADPS2,AMR,assoc,allVariants,chr7:122614044:A:G,G,0.04769,5.445000e-05,2.303000e-02,1.691,...,1918,4,2122,0.047686,3,79,1396,8,1486,0.028755
5849,CADPS2,AMR,assoc,allVariants,chr7:122620824:C:T,T,0.04406,1.779000e-05,7.524000e-03,1.805,...,1937,0,2122,0.044062,3,68,1415,0,1486,0.024899
5851,CADPS2,AMR,assoc,allVariants,chr7:122623423:G:A,A,0.04455,2.458000e-05,1.040000e-02,1.777,...,1934,1,2122,0.044554,3,70,1413,0,1486,0.025572
5852,CADPS2,AMR,assoc,allVariants,chr7:122623824:G:A,A,0.04383,2.175000e-05,9.202000e-03,1.795,...,1938,0,2122,0.043827,3,68,1415,0,1486,0.024899
5853,CADPS2,AMR,assoc,allVariants,chr7:122623836:T:C,C,0.04383,2.175000e-05,9.202000e-03,1.795,...,1938,0,2122,0.043827,3,68,1415,0,1486,0.024899
5854,CADPS2,AMR,assoc,allVariants,chr7:122624295:A:C,C,0.04415,1.704000e-05,7.209000e-03,1.807,...,1933,4,2122,0.044145,3,68,1414,1,1486,0.024916
5858,CADPS2,AMR,assoc,allVariants,chr7:122629484:G:A,A,0.03819,5.624000e-06,2.379000e-03,1.995,...,1962,1,2122,0.038190,1,56,1429,0,1486,0.019515
5889,CADPS2,AMR,assoc,allVariants,chr7:122658918:T:TA,TA,0.03972,8.447000e-05,3.573000e-02,1.761,...,1948,7,2122,0.039716,2,64,1416,4,1486,0.022942
5967,CADPS2,AMR,assoc,allVariants,chr7:122721872:C:G,G,0.02227,8.873000e-06,3.753000e-03,0.5375,...,1975,56,2122,0.022265,3,110,1314,59,1486,0.040645
5978,CADPS2,AMR,assoc,allVariants,chr7:122741661:C:G,G,0.03004,5.229000e-06,2.212000e-03,0.5695,...,1941,58,2122,0.030039,7,130,1259,90,1486,0.051576
5984,CADPS2,AMR,assoc,allVariants,chr7:122773084:C:T,T,0.02974,9.376000e-07,3.966000e-04,0.5478,...,1946,54,2122,0.029739,8,133,1265,80,1486,0.052987
5999,CADPS2,AMR,assoc,allVariants,chr7:122821341:G:A,A,0.02970,5.572000e-07,2.357000e-04,0.5422,...,1949,51,2122,0.029696,8,135,1270,73,1486,0.053432
6009,CADPS2,AMR,assoc,allVariants,chr7:122841824:A:AC,AC,0.05584,2.194000e-05,9.279000e-03,1.663,...,1893,9,2122,0.055845,2,98,1385,1,1486,0.034343
7364,CADPS2,EAS,assoc,allVariants,chr7:122359647:C:G,G,0.01060,2.005000e-05,7.317000e-03,0.515,...,2957,63,3083,0.010596,3,104,2593,86,2786,0.020370
7389,CADPS2,EAS,assoc,allVariants,chr7:122397907:G:A,A,0.01032,7.385000e-05,2.696000e-02,0.5346,...,2990,31,3083,0.010321,3,99,2642,42,2786,0.019133
7617,CADPS2,EAS,assoc,allVariants,chr7:122707503:G:A,A,0.02127,4.055000e-06,1.480000e-03,0.5921,...,2929,27,3083,0.021270,2,190,2548,46,2786,0.035401
7632,CADPS2,EAS,assoc,allVariants,chr7:122757469:C:T,T,0.03746,7.194000e-05,2.626000e-02,0.7007,...,2855,0,3083,0.037464,8,277,2499,2,2786,0.052622
7641,CADPS2,EAS,assoc,allVariants,chr7:122799947:C:T,T,0.02447,6.818000e-05,2.489000e-02,0.6496,...,2916,18,3083,0.024470,3,199,2555,29,2786,0.037178
7650,CADPS2,EAS,assoc,allVariants,chr7:122824005:A:T,T,0.01424,1.069000e-04,3.903000e-02,0.5863,...,2968,29,3083,0.014244,2,128,2614,42,2786,0.024052
7658,CADPS2,EAS,assoc,allVariants,chr7:122841822:G:C,C,0.01425,1.068000e-04,3.898000e-02,0.5863,...,2967,30,3083,0.014248,2,128,2613,43,2786,0.024061

In [78]:
significant_stats_bonf.to_csv(f"{RESU_DIR}/{analysis}/CADPS2_{analysis}_assocglm_SignificantVariantsAdjusted.csv", index=False)

## Annotate significant variants

In [79]:
significant_stats[['chr', 'pos', 'ref', 'alt']] = significant_stats['ID'].str.split(':', expand=True)

# Prepare avinput DataFrame
avinput = significant_stats[['chr', 'pos', 'pos', 'ref', 'alt']]

# Save to tab-delimited file
avinput.to_csv(f'{RESU_DIR}/significant_variants.avinput', sep='\t', index=False, header=False)

/tmp/ipykernel_658/718702108.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_stats[['chr', 'pos', 'ref', 'alt']] = significant_stats['ID'].str.split(':', expand=True)
/tmp/ipykernel_658/718702108.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_stats[['chr', 'pos', 'ref', 'alt']] = significant_stats['ID'].str.split(':', expand=True)
/tmp/ipykernel_658/718702108.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_stats[['chr', 'pos', 'ref', 'alt']] = significant_stats['ID'].str.split(':', expand=True)
/tmp/ipykernel_658/718702108.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_stats[['chr', 'pos', 'ref', 'alt']] = significant_stats['ID'].str.split(':', expand=True)

In [80]:
BUILD = "hg38"
annotateClinvar = [
        "perl", f"{TOOL_DIR}/annovar/table_annovar.pl",
        f'{RESU_DIR}/significant_variants.avinput',
        f"{TOOL_DIR}/annovar/humandb/",
        "-buildver", f"{BUILD}",
        "-out", f'{RESU_DIR}/{analysis}/significant_variants',
        "-remove", 
        "-protocol", "clinvar_20250721",
        "-operation", "f",
        "--nopolish",
        "-nastring", ".",
    ]

subprocess.run(annotateClinvar, check=True)

-----------------------------------------------------------------
NOTICE: Processing operation=f protocol=clinvar_20250721
NOTICE: Finished reading 13 column headers for '-dbtype clinvar_20250721'

NOTICE: Running system command <annotate_variation.pl -filter -dbtype clinvar_20250721 -buildver hg38 -outfile /home/jupyter/workspace/ws_files/NahuTestR11/Results/NBA/significant_variants /home/jupyter/workspace/ws_files/NahuTestR11/Results/significant_variants.avinput /home/jupyter/tools/annovar/humandb/ -otherinfo>
NOTICE: the --dbtype clinvar_20250721 is assumed to be in generic ANNOVAR database format
NOTICE: Output file with variants matching filtering criteria is written to /home/jupyter/workspace/ws_files/NahuTestR11/Results/NBA/significant_variants.hg38_clinvar_20250721_dropped, and output file with other variants is written to /home/jupyter/workspace/ws_files/NahuTestR11/Results/NBA/significant_variants.hg38_clinvar_20250721_filtered
NOTICE: Processing next batch with 467 unique variants in 626 input lines
NOTICE: Database index loaded. Total number of bins is 183171 and the number of bins to be scanned is 16
NOTICE: Scanning filter database /home/jupyter/tools/annovar/humandb/hg38_clinvar_20250721.txt...Done
NOTICE: Variants with invalid input format are written to /home/jupyter/workspace/ws_files/NahuTestR11/Results/NBA/significant_variants.invalid_input
-----------------------------------------------------------------
NOTICE: Multianno output file is written to /home/jupyter/workspace/ws_files/NahuTestR11/Results/NBA/significant_variants.hg38_multianno.txt

CompletedProcess(args=['perl', '/home/jupyter/tools/annovar/table_annovar.pl', '/home/jupyter/workspace/ws_files/NahuTestR11/Results/significant_variants.avinput', '/home/jupyter/tools/annovar/humandb/', '-buildver', 'hg38', '-out', '/home/jupyter/workspace/ws_files/NahuTestR11/Results/NBA/significant_variants', '-remove', '-protocol', 'clinvar_20250721', '-operation', 'f', '--nopolish', '-nastring', '.'], returncode=0)

In [81]:
multianno = pd.read_csv(f'{RESU_DIR}/{analysis}/significant_variants.hg38_multianno.txt', sep='\t', header=0)
multianno['ID'] = multianno['Chr'] + ":" + multianno['Start'].astype(str) + ":" + multianno['Ref'] + ":" + multianno['Alt']

annotated_significant = pd.merge(significant_stats, multianno, how='inner', on='ID')
annotated_significant

,Gene,Ancestry,Analysis,Variant type,ID,A1,A1_FREQ,P,BONF,OR,...,CLNREVSTAT,CLNSIG,ONCDN,ONCDISDB,ONCREVSTAT,ONC,SCIDN,SCIDISDB,SCIREVSTAT,SCI
0,CADPS2,AAC,assoc,allVariants,chr7:122636614:C:T,T,0.042020,0.017990,1.0,1.698,...,.,.,.,.,.,.,.,.,.,.
1,CADPS2,AAC,assoc,allVariants,chr7:122636614:C:T,T,0.042020,0.017990,1.0,1.698,...,.,.,.,.,.,.,.,.,.,.
2,CADPS2,AAC,assoc,allVariants,chr7:122642574:T:C,C,0.042020,0.013630,1.0,1.741,...,.,.,.,.,.,.,.,.,.,.
3,CADPS2,AAC,assoc,allVariants,chr7:122642574:T:C,C,0.042020,0.013630,1.0,1.741,...,.,.,.,.,.,.,.,.,.,.
4,CADPS2,AAC,assoc,allVariants,chr7:122830346:T:A,A,0.062760,0.003228,1.0,1.722,...,.,.,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,CADPS2,CAH,glm,allVariants,chr7:122736871:T:C,C,0.016378,0.012005,1.0,0.350223,...,.,.,.,.,.,.,.,.,.,.
904,CADPS2,CAH,glm,allVariants,chr7:122751933:C:G,G,0.010671,0.024358,1.0,5.50309,...,.,.,.,.,.,.,.,.,.,.
905,CADPS2,CAH,glm,allVariants,chr7:122863970:C:T,T,0.010892,0.046510,1.0,3.60987,...,.,.,.,.,.,.,.,.,.,.
906,CADPS2,CAH,glm,allVariants,chr7:122874108:T:C,C,0.010958,0.047693,1.0,3.53735,...,.,.,.,.,.,.,.,.,.,.
907,CADPS2,CAH,glm,allVariants,chr7:122880617:T:C,C,0.023779,0.035897,1.0,0.481116,...,.,.,.,.,.,.,.,.,.,.

In [82]:
significant_stats_bonf.to_csv(f"{RESU_DIR}/{analysis}/CADPS2_{analysis}_assocglm_SignificantVariantsAnnotated.csv", index=False)

## To-Do list

- Make all analyses into one single function, and call it with different assoc models, ANCESTRIES, variant groups in parallel

- Check exonic GLM +

- Add all outputs in single df by ANCESTRIES in first column, keep p<0.05